In [1]:
import pyscrew
import matplotlib.pyplot as plt
import pandas as pd
from neuralop.models import FNO
from sklearn.preprocessing import OneHotEncoder

In [2]:
# Load data from the thread degradation scenario (s02)
data_v2 = pyscrew.get_data(scenario="s02", handle_duplicates="first", handle_missings="mean",cache_dir="~/.cache/pyscrew", force_download=False, target_length=800)

# Access the measurements and labels
x_values_v2 = data_v2["torque_values"]
y_values_v2 = data_v2["class_values"]
usage_values_v2 = data_v2["workpiece_usage"]

2026-05-20 15:57:01 - INFO - pyscrew.main - Starting data retrieval for scenario: s02 (surface-friction)
2026-05-20 15:57:01 - INFO - pyscrew.pipeline.loading - Using cache directory (absolute): C:\Users\Patrick\.cache\pyscrew
2026-05-20 15:57:01 - INFO - pyscrew.pipeline.loading - Beginning data extraction for scenario 's02_variations-in-surface-friction.zip' (force=False)
2026-05-20 15:57:01 - INFO - pyscrew.pipeline.loading - Verifying MD5 checksum for 's02_variations-in-surface-friction.zip'...
2026-05-20 15:57:01 - INFO - pyscrew.pipeline.loading - Checksum verification successful for 's02_variations-in-surface-friction.zip' (MD5: 0bc948a6e8c6e83f72dbe36973131558)
2026-05-20 15:57:01 - INFO - pyscrew.pipeline.loading - Using existing verified file 's02_variations-in-surface-friction.zip' at: C:\Users\Patrick\.cache\pyscrew\archives\s02_variations-in-surface-friction.zip
2026-05-20 15:57:02 - INFO - pyscrew.pipeline.loading - Using existing extracted data for scenario 's02_variations-in-surface-friction' at: C:\Users\Patrick\.cache\pyscrew\extracted\s02_variations-in-surface-friction\json
2026-05-20 15:57:02 - INFO - pyscrew.core.dataset - Selected 12500 files
2026-05-20 15:57:10 - INFO - pyscrew.core.dataset - Successfully loaded 12500 screw runs
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.processing - Adding input_logging transformer to pipeline
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.processing - Adding step_unpacking transformer to pipeline
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.processing - Adding duplicate handling with first
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.processing - Adding handling of missings with mean
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.processing - Adding length normalization with 800
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.processing - Adding dataset conversion with list
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.processing - Adding output_logging transformer to pipeline
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.transformers.pipeline_logging - Input - Fit: Dataset contains 12500 runs
2026-05-20 15:57:10 - INFO - pyscrew.pipeline.transformers.pipeline_logging - time values: 12500 runs
2026-05-20 15:57:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - torque values: 12500 runs
2026-05-20 15:57:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - angle values: 12500 runs
2026-05-20 15:57:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - gradient values: 12500 runs
2026-05-20 15:57:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - Input - Transform: Processing 12500 runs
2026-05-20 15:57:11 - INFO - pyscrew.pipeline.transformers.unpack_steps - Selected measurements: ['time values', 'torque values', 'angle values', 'gradient values']
2026-05-20 15:57:12 - INFO - pyscrew.pipeline.transformers.unpack_steps - Unpacked 12500 runs with 8,679,740 total measurements
2026-05-20 15:57:15 - INFO - pyscrew.pipeline.transformers.handle_duplicates - Completed duplicate removal using 'first' method
2026-05-20 15:57:15 - INFO - pyscrew.pipeline.transformers.handle_duplicates - Processed 12,500 series with 8,679,740 total points
2026-05-20 15:57:15 - INFO - pyscrew.pipeline.transformers.handle_duplicates - Found 56,466 true duplicates (94.5%) and 3,292 value differences (5.5%)
2026-05-20 15:57:15 - INFO - pyscrew.pipeline.transformers.handle_duplicates - Removed 59,758 points (-0.7% of total)
2026-05-20 15:57:15 - INFO - pyscrew.pipeline.transformers.handle_duplicates - Average 4.78 points removed per series

2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_missings - Completed missing interpolation using 'mean' method (interval=0.0012)
2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_missings - Processed 12,500 series with 8,619,982 total points
2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_missings - Found gaps - min: 0.0012s, max: 0.1128s, avg: 0.0013s
2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_missings - Added 484,205 points (+5.62% of total)
2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_missings - Average 38.7 points added per series
2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_lengths - Starting to apply equal lengths.

2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_lengths - - 'target_length' : 800
2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_lengths - - 'padding_value' : 0.0
2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_lengths - - 'padding_position' : post
2026-05-20 15:59:09 - INFO - pyscrew.pipeline.transformers.handle_lengths - - 'cutoff_position' : post
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.handle_lengths - Finished applying equal lengths to the screw driving data.
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.handle_lengths - - Total screw runs loaded:	12500
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.handle_lengths - - Average change of length:	728.33 -> 800.00
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.handle_lengths - - Total points before normalization:	9,104,187
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.handle_lengths - - Total points after normalization:	10,000,000
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.convert_dataset - Output format is 'list' - keeping the default format
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - Output - Fit: Dataset contains 12500 runs
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - time_values: 12500 runs
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - torque_values: 12500 runs
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - angle_values: 12500 runs
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - gradient_values: 12500 runs
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - step_values: 12500 runs
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - class_values: 12500 values
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - workpiece_location: 12500 values
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - workpiece_usage: 12500 values
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - workpiece_result: 12500 values
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - scenario_condition: 12500 values
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - scenario_exception: 12500 values
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - Output - Transform: Processing 12500 runs
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - Dataset contains 11 fields: 6 measurements, 5 metadata fields
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - time_values: 12500 runs, avg 800.0 points per run
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - torque_values: 12500 runs, avg 800.0 points per run
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - angle_values: 12500 runs, avg 800.0 points per run
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - gradient_values: 12500 runs, avg 800.0 points per run
2026-05-20 15:59:11 - INFO - pyscrew.pipeline.transformers.pipeline_logging - step_values: 12500 runs, avg 800.0 points per run
2026-05-20 15:59:12 - INFO - pyscrew.pipeline.validating - Validating processed data for scenario 's02'
2026-05-20 15:59:15 - INFO - pyscrew.pipeline.validating - Data validation passed: 4 measurement types and 7 metadata fields with 12500 runs

In [3]:
data_v2_df = pd.DataFrame(data_v2)

In [4]:
data_v2_df.head()

,time_values,torque_values,angle_values,gradient_values,step_values,class_values,workpiece_location,workpiece_usage,workpiece_result,scenario_condition,scenario_exception
0,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[0.067, 0.077, 0.126, 0.087, 0.089, 0.097, 0.0...","[0.5, 1.25, 2.25, 3.75, 5.0, 6.25, 7.5, 8.75, ...","[0.0, 0.0, 0.0298, 0.0214, 0.0064, 0.0023, -0....","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,left,0,OK,normal,0
1,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[-0.005, 0.008, 0.061, 0.069, 0.104, 0.124, 0....","[0.0, 0.25, 0.75, 1.5, 2.5, 4.0, 5.25, 6.5, 7....","[0.0, 0.0, 0.0, 0.0, 0.0287, 0.0282, 0.0091, 0...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,right,0,OK,normal,0
2,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[-0.003, 0.01, 0.039, 0.099, 0.102, 0.087, 0.0...","[0.0, 0.5, 1.25, 2.25, 3.5, 4.75, 6.0, 7.5, 8....","[0.0, 0.0, 0.0, 0.0196, 0.0223, 0.0211, 0.0096...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,left,1,OK,normal,0
3,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[0.081, 0.059, 0.12, 0.077, 0.043, 0.059, 0.06...","[0.75, 1.75, 2.75, 4.0, 5.25, 6.5, 7.75, 9.25,...","[0.0, 0.0, 0.0261, 0.0207, 0.0, -0.0036, -0.00...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,right,1,OK,normal,0
4,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[-0.003, -0.0012, 0.0006, 0.0024, 0.0042, 0.00...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 1.5, 2.5, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.025...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,left,2,OK,normal,0

In [5]:
"""
@author: Modified code from Zongyi Li, modified by QueensGambit
This file is the Fourier Neural Operator for 1D problem such as the (time-independent) Burgers equation discussed in Section 5.1 in the [paper](https://arxiv.org/pdf/2010.08895.pdf).
"""

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.parameter import Parameter
import matplotlib.pyplot as plt

import operator
from functools import reduce
from functools import partial
from timeit import default_timer
#from fourier-neural-operator.utilities3 import *

#from Adam import Adam

torch.manual_seed(0)
np.random.seed(0)

In [6]:
################################################################
#  1d fourier layer
################################################################
class SpectralConv1d(nn.Module):
    def __init__(self, in_channels, out_channels, modes1):
        super(SpectralConv1d, self).__init__()

        """
        1D Fourier layer. It does FFT, linear transform, and Inverse FFT.    
        """

        self.in_channels = in_channels
        self.out_channels = out_channels
        self.modes1 = modes1  #Number of Fourier modes to multiply, at most floor(N/2) + 1

        self.scale = (1 / (in_channels*out_channels))
        self.weights1 = nn.Parameter(self.scale * torch.rand(in_channels, out_channels, self.modes1, dtype=torch.cfloat))

    # Complex multiplication
    def compl_mul1d(self, input, weights):
        # (batch, in_channel, x ), (in_channel, out_channel, x) -> (batch, out_channel, x)
        return torch.einsum("bix,iox->box", input, weights)

    def forward(self, x):
        batchsize = x.shape[0]
        #Compute Fourier coeffcients up to factor of e^(- something constant)
        x_ft = torch.fft.rfft(x)

        # Multiply relevant Fourier modes
        out_ft = torch.zeros(batchsize, self.out_channels, x.size(-1)//2 + 1,  device=x.device, dtype=torch.cfloat)
        out_ft[:, :, :self.modes1] = self.compl_mul1d(x_ft[:, :, :self.modes1], self.weights1)

        #Return to physical space
        x = torch.fft.irfft(out_ft, n=x.size(-1))
        return x

class FNO1d(nn.Module):
    def __init__(self, modes, width, n_classes):
        super(FNO1d, self).__init__()

        """
        The overall network. It contains 4 layers of the Fourier layer.
        1. Lift the input to the desire channel dimension by self.fc0 .
        2. 4 layers of the integral operators u' = (W + K)(u).
            W defined by self.w; K defined by self.conv .
        3. Project from the channel space to the output space by self.fc1 and self.fc2 .
        
        input: the solution of the initial condition and location (a(x), x)
        input shape: (batchsize, x=s, c=2)
        output: the solution of a later timestep
        output shape: (batchsize, x=s, c=1)
        """

        self.modes1 = modes
        self.width = width
        self.padding = 2 # pad the domain if input is non-periodic
        self.fc0 = nn.Linear(2, self.width) # input channel is 2: (a(x), x)

        self.conv0 = SpectralConv1d(self.width, self.width, self.modes1)
        self.conv1 = SpectralConv1d(self.width, self.width, self.modes1)
        self.conv2 = SpectralConv1d(self.width, self.width, self.modes1)
        self.conv3 = SpectralConv1d(self.width, self.width, self.modes1)
        self.w0 = nn.Conv1d(self.width, self.width, 1)
        self.w1 = nn.Conv1d(self.width, self.width, 1)
        self.w2 = nn.Conv1d(self.width, self.width, 1)
        self.w3 = nn.Conv1d(self.width, self.width, 1)

        self.fc1 = nn.Linear(self.width, 128)
        self.fc2 = nn.Linear(128, n_classes)

    def forward(self, x):
        grid = self.get_grid(x.shape, x.device)
        x = torch.cat((x, grid), dim=-1)
        x = self.fc0(x)
        x = x.permute(0, 2, 1)
        # x = F.pad(x, [0,self.padding]) # pad the domain if input is non-periodic

        x1 = self.conv0(x)
        x2 = self.w0(x)
        x = x1 + x2
        x = F.gelu(x)

        x1 = self.conv1(x)
        x2 = self.w1(x)
        x = x1 + x2
        x = F.gelu(x)

        x1 = self.conv2(x)
        x2 = self.w2(x)
        x = x1 + x2
        x = F.gelu(x)

        x1 = self.conv3(x)
        x2 = self.w3(x)
        x = x1 + x2

        # 1. Global Pooling: Average across the 1000 time steps
        # This collapses the sequence dimension
        x = torch.mean(x, dim=-1) # New shape: (batch, width)

        # x = x[..., :-self.padding] # pad the domain if input is non-periodic
        #x = x.permute(0, 2, 1)
        x = self.fc1(x)
        x = F.gelu(x)
        x = self.fc2(x)
        return x

    def get_grid(self, shape, device):
        batchsize, size_x = shape[0], shape[1]
        gridx = torch.tensor(np.linspace(0, 1, size_x), dtype=torch.float)
        gridx = gridx.reshape(1, size_x, 1).repeat([batchsize, 1, 1])
        return gridx.to(device)
    
class FNO2d(nn.Module):
    def __init__(self, modes, width, n_classes, input_channels = 1):
        super(FNO2d, self).__init__()

        """
        The overall network. It contains 4 layers of the Fourier layer.
        1. Lift the input to the desire channel dimension by self.fc0 .
        2. 4 layers of the integral operators u' = (W + K)(u).
            W defined by self.w; K defined by self.conv .
        3. Project from the channel space to the output space by self.fc1 and self.fc2 .
        
        input: the solution of the initial condition and location (a(x), x)
        input shape: (batchsize, x=s, c=2)
        output: the solution of a later timestep
        output shape: (batchsize, x=s, c=1)
        """

        self.modes1 = modes
        self.width = width
        self.padding = 2 # pad the domain if input is non-periodic
        self.fc0 = nn.Linear(input_channels +1, self.width) # input channel is flexibel for more features e.g. torque + angle

        self.conv0 = SpectralConv1d(self.width, self.width, self.modes1)
        self.conv1 = SpectralConv1d(self.width, self.width, self.modes1)
        self.conv2 = SpectralConv1d(self.width, self.width, self.modes1)
        self.conv3 = SpectralConv1d(self.width, self.width, self.modes1)
        self.w0 = nn.Conv1d(self.width, self.width, 1)
        self.w1 = nn.Conv1d(self.width, self.width, 1)
        self.w2 = nn.Conv1d(self.width, self.width, 1)
        self.w3 = nn.Conv1d(self.width, self.width, 1)

        self.fc1 = nn.Linear(self.width, 128)
        self.fc2 = nn.Linear(128, n_classes)

    def forward(self, x):
        grid = self.get_grid(x.shape, x.device)
        x = torch.cat((x, grid), dim=-1)
        x = self.fc0(x)
        x = x.permute(0, 2, 1)
        # x = F.pad(x, [0,self.padding]) # pad the domain if input is non-periodic

        x1 = self.conv0(x)
        x2 = self.w0(x)
        x = x1 + x2
        x = F.gelu(x)

        x1 = self.conv1(x)
        x2 = self.w1(x)
        x = x1 + x2
        x = F.gelu(x)

        x1 = self.conv2(x)
        x2 = self.w2(x)
        x = x1 + x2
        x = F.gelu(x)

        x1 = self.conv3(x)
        x2 = self.w3(x)
        x = x1 + x2

        # 1. Global Pooling: Average across the 1000 time steps
        # This collapses the sequence dimension
        x = torch.mean(x, dim=-1) # New shape: (batch, width)

        # x = x[..., :-self.padding] # pad the domain if input is non-periodic
        #x = x.permute(0, 2, 1)
        x = self.fc1(x)
        x = F.gelu(x)
        x = self.fc2(x)
        return x

    def get_grid(self, shape, device):
        batchsize, size_x = shape[0], shape[1]
        gridx = torch.tensor(np.linspace(0, 1, size_x), dtype=torch.float)
        gridx = gridx.reshape(1, size_x, 1).repeat([batchsize, 1, 1])
        return gridx.to(device)

In [9]:
################################################################
#  configurations
################################################################
ntrain = 1000
ntest = 100

sub = 2**3 #subsampling rate
h = 2**13 // sub #total grid size divided by the subsampling rate
s = h

batch_size = 20
learning_rate = 0.001

epochs = 500
step_size = 50
gamma = 0.5

modes = 16
width = 64

In [10]:
len(data_v2_df["torque_values"])

12500

In [11]:
x_data = np.array(data_v2_df["torque_values"].tolist())
y_data = np.array(data_v2_df["class_values"].tolist())

In [12]:
y_data.shape

(12500,)

In [13]:
x_data.shape

(12500, 800)

In [14]:
from sklearn.utils import shuffle

In [15]:
################################################################
# read data
################################################################

# Data is of the shape (number of samples, grid size)
#dataloader = MatReader('data/burgers_data_R10.mat')
#x_data = dataloader.read_field('a')[:,::sub]
#y_data = dataloader.read_field('u')[:,::sub]
x_data = np.array(data_v2_df['torque_values'].tolist())
y_data = np.array(data_v2_df['class_values'].tolist())
usage = np.array(data_v2_df['workpiece_usage'].tolist())

# Reshape is required because OneHotEncoder expects a 2D array (samples, features)
data_reshaped = y_data.reshape(-1, 1)

# Initialize and transform
encoder = OneHotEncoder(sparse_output=False) # Use sparse=False to get a dense numpy array
one_hot = encoder.fit_transform(data_reshaped)

print(one_hot)
# To see the labels corresponding to the columns:
print(encoder.get_feature_names_out())

split_ratio = 0.65
n_samples = len(x_data)
split_idx = int(n_samples * split_ratio)

X_s, y_s = shuffle(x_data, one_hot)

x_train = X_s[:split_idx,:]
y_train = y_s[:split_idx,:]
x_test = X_s[split_idx:,:]
y_test = y_s[split_idx:,:]

x_train_tensor = torch.from_numpy(x_train).float().unsqueeze(-1)
y_train_tensor = torch.from_numpy(y_train).float().argmax(axis=1)

x_test_tensor = torch.from_numpy(x_test).float().unsqueeze(-1)
y_test_tensor = torch.from_numpy(y_test).float().argmax(axis=1)

#x_train = x_train.reshape(ntrain,s,1)
#x_test = x_test.reshape(ntest,s,1)

#train_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(x_train_tensor, y_train_tensor), batch_size=batch_size, shuffle=True)
#test_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(x_test_tensor, y_test_tensor), batch_size=batch_size, shuffle=False)

# model
model = FNO1d(modes, width, n_classes=8).cuda()
#model = FNO(n_modes=(64, 64),
#               hidden_channels=64,
#               in_channels=1,
#               out_channels=1)

#print(count_params(model))
model_2d = FNO2d(modes, width, n_classes=8, input_channels=2).cuda()

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
['x0_001_control-group' 'x0_101_used-upper-workpiece'
 'x0_201_lubricant-water' 'x0_202_lubricant-oil-based'
 'x0_301_sanding-coarse' 'x0_302_sanding-fine' 'x0_401_plastic-adhesive'
 'x0_402_surface-chipped']

In [16]:
x_train.shape

(8125, 800)

In [17]:
y_train.shape

(8125, 8)

In [18]:
y_test_tensor.shape

torch.Size([4375])

In [19]:
n_classes = y_train.shape[1]
n_classes

8

In [20]:
#loss function with rel/abs Lp loss
class LpLoss(object):
    def __init__(self, d=2, p=2, size_average=True, reduction=True):
        super(LpLoss, self).__init__()

        #Dimension and Lp-norm type are postive
        assert d > 0 and p > 0

        self.d = d
        self.p = p
        self.reduction = reduction
        self.size_average = size_average

    def abs(self, x, y):
        num_examples = x.size()[0]

        #Assume uniform mesh
        h = 1.0 / (x.size()[1] - 1.0)

        all_norms = (h**(self.d/self.p))*torch.norm(x.view(num_examples,-1) - y.view(num_examples,-1), self.p, 1)

        if self.reduction:
            if self.size_average:
                return torch.mean(all_norms)
            else:
                return torch.sum(all_norms)

        return all_norms

    def rel(self, x, y):
        num_examples = x.size()[0]

        diff_norms = torch.norm(x.reshape(num_examples,-1) - y.reshape(num_examples,-1), self.p, 1)
        y_norms = torch.norm(y.reshape(num_examples,-1), self.p, 1)

        if self.reduction:
            if self.size_average:
                return torch.mean(diff_norms/y_norms)
            else:
                return torch.sum(diff_norms/y_norms)

        return diff_norms/y_norms

    def __call__(self, x, y):
        return self.rel(x, y)

In [21]:
import torch
from torchmetrics.classification import MulticlassAccuracy, MulticlassF1Score

# Assuming n_classes = 8 based on your y_train.shape
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

acc_metric = MulticlassAccuracy(num_classes=n_classes).to(device)
f1_metric = MulticlassF1Score(num_classes=n_classes).to(device)

In [ ]:

################################################################
# training and evaluation
################################################################
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=gamma)

myloss = LpLoss(size_average=False)

#early stopping parameter
patience = 30
best_test_f1 = -np.inf
patience_counter=0
best_model_state=None
for ep in range(epochs):
    model.train()
    t1 = default_timer()
    train_cross_entropy = 0
    #train_l2 = 0
    for x, y in train_loader:
        x, y = x.cuda(), y.cuda()
        optimizer.zero_grad()
        out = model(x)
        #mse = F.mse_loss(out.view(batch_size, -1), y.view(batch_size, -1), reduction='mean')
        cross_entropy = F.cross_entropy(out, y)
        #cross_entropy = F.cross_entropy(out.view(batch_size, -1), y.view(batch_size, -1))
        #l2 = myloss(out.view(batch_size, -1), y.view(batch_size, -1))
        #l2.backward() # use the l2 relative loss
        cross_entropy.backward()
        optimizer.step()
        train_cross_entropy += cross_entropy.item()
        #train_l2 += l2.item()
        # 3. Update Metrics
        acc_metric.update(out, y)
        f1_metric.update(out, y)
    
    # 4. Compute final values for the epoch
    epoch_acc = acc_metric.compute()
    epoch_f1 = f1_metric.compute()
    print(f"Train Accuracy: {epoch_acc:.4f}, F1 Score: {epoch_f1:.4f}")

    acc_metric.reset()  # <--- RESET FOR TEST PHASE
    f1_metric.reset()

    scheduler.step()
    model.eval()
    test_cross_entropy = 0.0
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.cuda(), y.cuda()

            out = model(x)
            test_cross_entropy = F.cross_entropy(out, y)  # ruft nur den letzten batch auf und test_cross_entropy wird üebrschrieben udn nciht aufsummiert
            #test_l2 += myloss(out.view(batch_size, -1), y.view(batch_size, -1)).item()

            # 3. Update Metrics
            acc_metric.update(out, y)
            f1_metric.update(out, y)
    
    # 4. Compute final values for the epoch
    epoch_acc = acc_metric.compute()
    epoch_f1 = f1_metric.compute()
    
    print(f"Test Accuracy: {epoch_acc:.4f}, F1 Score: {epoch_f1:.4f}")
    
    train_cross_entropy /= len(train_loader) # hier wird mit test_cross_entropy = F.cross_entropy(out, y) lediglich der letzte batchaufgerufen
    #train_l2 /= ntrain
    #test_l2 /= ntest
    t2 = default_timer()
    print(ep, t2-t1, train_cross_entropy, test_cross_entropy)
    if epoch_f1 > best_test_f1:
        best_test_f1 = epoch_f1
        best_model_state = model.state_dict().copy() 
        patience_counter = 0
        print(f"Neue bestes f1: {best_test_f1:.4f}")
    else:
        patience_counter += 1
        if patience_counter >= patience:
            print(f"Early stopped da keine Verbesserung nach {ep+1} epochen")
            if best_model_state is not None: 
                model.load_state_dict(best_model_state)
            break

# torch.save(model, 'model/ns_fourier_burgers')
pred = torch.zeros(y_test.shape)
index = 0
test_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(x_test_tensor, y_test_tensor), batch_size=1, shuffle=False)
with torch.no_grad():
    for x, y in test_loader:
        test_l2 = 0
        x, y = x.cuda(), y.cuda()

        out = model(x) #.view(-1)
        pred[index] = out

        test_cross_entropy = F.cross_entropy(out, y)
        #test_l2 += myloss(out.view(1, -1), y.view(1, -1)).item()
        print(index, test_cross_entropy)
        index = index + 1

# scipy.io.savemat('pred/burger_test.mat', mdict={'pred': pred.cpu().numpy()})

Train Accuracy: 0.5746, F1 Score: 0.5726
Test Accuracy: 0.4116, F1 Score: 0.4029
0 12.418911300002947 0.7719479263268173 tensor(0.1891, device='cuda:0')
Neue bestes f1: 0.4029
Train Accuracy: 0.5918, F1 Score: 0.5884
Test Accuracy: 0.3927, F1 Score: 0.3860
1 12.859266999999818 0.719230580864433 tensor(0.5658, device='cuda:0')
Train Accuracy: 0.5907, F1 Score: 0.5912
Test Accuracy: 0.4131, F1 Score: 0.4088
2 12.572723199999018 0.6802452021353954 tensor(0.2162, device='cuda:0')
Neue bestes f1: 0.4088
Train Accuracy: 0.6162, F1 Score: 0.6152
Test Accuracy: 0.4034, F1 Score: 0.4039
3 14.016685200003849 0.6260219846076402 tensor(0.5317, device='cuda:0')
Train Accuracy: 0.6219, F1 Score: 0.6240
Test Accuracy: 0.4095, F1 Score: 0.4032
4 13.682897700004105 0.6012273954744713 tensor(0.2195, device='cuda:0')
Train Accuracy: 0.6365, F1 Score: 0.6349
Test Accuracy: 0.4113, F1 Score: 0.4083
5 13.578654799996002 0.5755950745918241 tensor(0.3089, device='cuda:0')
Train Accuracy: 0.6463, F1 Score: 0.6472
Test Accuracy: 0.3943, F1 Score: 0.3907
6 12.459178400000383 0.5323049708724901 tensor(0.0081, device='cuda:0')
Train Accuracy: 0.6501, F1 Score: 0.6518
Test Accuracy: 0.4013, F1 Score: 0.3996
7 12.53991269999824 0.5029136271602691 tensor(0.2315, device='cuda:0')
Train Accuracy: 0.6615, F1 Score: 0.6608
Test Accuracy: 0.4152, F1 Score: 0.4101
8 12.740040800003044 0.46996375640135724 tensor(0.4032, device='cuda:0')
Neue bestes f1: 0.4101
Train Accuracy: 0.6694, F1 Score: 0.6693
Test Accuracy: 0.4135, F1 Score: 0.4095
9 12.198876000002201 0.46151821952340644 tensor(0.5666, device='cuda:0')
Train Accuracy: 0.6785, F1 Score: 0.6767
Test Accuracy: 0.4073, F1 Score: 0.4047
10 12.650193599998602 0.4310736954578311 tensor(1.0798, device='cuda:0')
Train Accuracy: 0.6927, F1 Score: 0.6920
Test Accuracy: 0.4108, F1 Score: 0.4063
11 12.60638789999939 0.37392357691060707 tensor(0.1368, device='cuda:0')
Train Accuracy: 0.6888, F1 Score: 0.6909
Test Accuracy: 0.4126, F1 Score: 0.4102
12 12.942263900004036 0.4041504973422104 tensor(0.0056, device='cuda:0')
Neue bestes f1: 0.4102
Train Accuracy: 0.7006, F1 Score: 0.6999
Test Accuracy: 0.4028, F1 Score: 0.3998
13 12.325858600001084 0.35314038859941155 tensor(1.1061, device='cuda:0')
Train Accuracy: 0.7041, F1 Score: 0.7031
Test Accuracy: 0.4088, F1 Score: 0.4060
14 12.815455300005851 0.3274180713391128 tensor(0.3752, device='cuda:0')
Train Accuracy: 0.7071, F1 Score: 0.7067
Test Accuracy: 0.3811, F1 Score: 0.3768
15 12.408116200000222 0.3380110995702134 tensor(0.7902, device='cuda:0')
Train Accuracy: 0.7018, F1 Score: 0.7039
Test Accuracy: 0.3924, F1 Score: 0.3905
16 12.70185869999841 0.31933739686188006 tensor(0.0143, device='cuda:0')
Train Accuracy: 0.7223, F1 Score: 0.7261
Test Accuracy: 0.3925, F1 Score: 0.3947
17 13.652943599998252 0.26278680258634196 tensor(0.1058, device='cuda:0')
Train Accuracy: 0.7203, F1 Score: 0.7217
Test Accuracy: 0.3875, F1 Score: 0.3872
18 12.312739299995883 0.27512536771796847 tensor(1.5995, device='cuda:0')
Train Accuracy: 0.7142, F1 Score: 0.7147
Test Accuracy: 0.4002, F1 Score: 0.4039
19 12.608325900000636 0.2834266753276897 tensor(0.0539, device='cuda:0')
Train Accuracy: 0.7384, F1 Score: 0.7409
Test Accuracy: 0.4014, F1 Score: 0.4009
20 12.314245599998685 0.22216340361725934 tensor(0.8531, device='cuda:0')
Train Accuracy: 0.7331, F1 Score: 0.7324
Test Accuracy: 0.4019, F1 Score: 0.3993
21 12.270673299994087 0.2374061803523387 tensor(3.9571, device='cuda:0')
Train Accuracy: 0.7237, F1 Score: 0.7248
Test Accuracy: 0.3966, F1 Score: 0.4011
22 12.53360860000248 0.27265707292211877 tensor(0.9188, device='cuda:0')
Train Accuracy: 0.7403, F1 Score: 0.7443
Test Accuracy: 0.4007, F1 Score: 0.3976
23 12.378192899996066 0.20960282134372712 tensor(0.0204, device='cuda:0')
Train Accuracy: 0.7380, F1 Score: 0.7376
Test Accuracy: 0.4036, F1 Score: 0.4015
24 12.584479400000419 0.21002183305854732 tensor(0.9891, device='cuda:0')
Train Accuracy: 0.7405, F1 Score: 0.7411
Test Accuracy: 0.3931, F1 Score: 0.3916
25 12.695007300004363 0.2192614291741968 tensor(3.3231, device='cuda:0')
Train Accuracy: 0.7376, F1 Score: 0.7372
Test Accuracy: 0.3976, F1 Score: 0.3956
26 13.223270499998762 0.20309608052564782 tensor(0.1146, device='cuda:0')
Train Accuracy: 0.7460, F1 Score: 0.7449
Test Accuracy: 0.4002, F1 Score: 0.3975
27 12.136999599999399 0.1768125930494407 tensor(7.1385, device='cuda:0')
Train Accuracy: 0.7444, F1 Score: 0.7466
Test Accuracy: 0.3955, F1 Score: 0.3954
28 12.402046800001699 0.19227058900387486 tensor(1.8038, device='cuda:0')
Train Accuracy: 0.7420, F1 Score: 0.7452
Test Accuracy: 0.3838, F1 Score: 0.3849
29 12.345553999999538 0.19904474049568616 tensor(0.1589, device='cuda:0')
Train Accuracy: 0.7495, F1 Score: 0.7535
Test Accuracy: 0.3975, F1 Score: 0.3969
30 12.20272219999606 0.14672609077679583 tensor(1.8775, device='cuda:0')
Train Accuracy: 0.7493, F1 Score: 0.7515
Test Accuracy: 0.3948, F1 Score: 0.3951
31 12.58820410000044 0.17520062112837517 tensor(5.1535, device='cuda:0')
Train Accuracy: 0.7525, F1 Score: 0.7536
Test Accuracy: 0.3836, F1 Score: 0.3812
32 12.26505829999951 0.15848863589364567 tensor(0.2918, device='cuda:0')
Train Accuracy: 0.7400, F1 Score: 0.7396
Test Accuracy: 0.3914, F1 Score: 0.3889
33 12.20360090000031 0.2018492981683948 tensor(1.7051, device='cuda:0')
Train Accuracy: 0.7594, F1 Score: 0.7601
Test Accuracy: 0.3975, F1 Score: 0.3865
34 12.260853100000531 0.11846451994365755 tensor(3.5517, device='cuda:0')
Train Accuracy: 0.7519, F1 Score: 0.7498
Test Accuracy: 0.3952, F1 Score: 0.3932
35 12.286493500003417 0.1673745245075526 tensor(2.5162, device='cuda:0')
Train Accuracy: 0.7537, F1 Score: 0.7528
Test Accuracy: 0.3910, F1 Score: 0.3891
36 12.365540099999635 0.15087487482687764 tensor(1.8944, device='cuda:0')
Train Accuracy: 0.7589, F1 Score: 0.7570
Test Accuracy: 0.3991, F1 Score: 0.3962
37 12.134120899994741 0.1239210462526027 tensor(3.4789, device='cuda:0')
Train Accuracy: 0.7437, F1 Score: 0.7437
Test Accuracy: 0.4055, F1 Score: 0.4019
38 12.298264999997627 0.19704219067803325 tensor(0.0512, device='cuda:0')
Train Accuracy: 0.7655, F1 Score: 0.7636
Test Accuracy: 0.3975, F1 Score: 0.3972
39 12.367794100005995 0.11662566540442425 tensor(3.5159, device='cuda:0')
Train Accuracy: 0.7634, F1 Score: 0.7651
Test Accuracy: 0.3843, F1 Score: 0.3812
40 12.428885599998466 0.10865189485121472 tensor(2.0766, device='cuda:0')
Train Accuracy: 0.7464, F1 Score: 0.7492
Test Accuracy: 0.3968, F1 Score: 0.3936
41 12.061364699999103 0.16531839896982 tensor(0.1004, device='cuda:0')
Train Accuracy: 0.7677, F1 Score: 0.7660
Test Accuracy: 0.3838, F1 Score: 0.3818
42 12.165642100000696 0.09704987513455185 tensor(0.0041, device='cuda:0')
Early stopped da keine Verbesserung nach 43 epochen
0 tensor(4.4182, device='cuda:0')
1 tensor(0.0028, device='cuda:0')
2 tensor(3.1369, device='cuda:0')
3 tensor(3.5571, device='cuda:0')
4 tensor(0.4045, device='cuda:0')
5 tensor(0.5019, device='cuda:0')
6 tensor(0.0227, device='cuda:0')
7 tensor(5.5113, device='cuda:0')
8 tensor(3.2225, device='cuda:0')
9 tensor(4.7090, device='cuda:0')
10 tensor(9.2154, device='cuda:0')
11 tensor(7.1525e-06, device='cuda:0')
12 tensor(11.9881, device='cuda:0')
13 tensor(4.1387, device='cuda:0')
14 tensor(1.1025, device='cuda:0')
15 tensor(0.0010, device='cuda:0')
16 tensor(5.1957, device='cuda:0')
17 tensor(0.4176, device='cuda:0')
18 tensor(8.4383, device='cuda:0')
19 tensor(1.5206, device='cuda:0')
20 tensor(18.4501, device='cuda:0')
21 tensor(5.1402, device='cuda:0')
22 tensor(0.0079, device='cuda:0')
23 tensor(0.0264, device='cuda:0')
24 tensor(0.3659, device='cuda:0')
25 tensor(1.7029, device='cuda:0')
26 tensor(15.0403, device='cuda:0')
27 tensor(2.7898, device='cuda:0')
28 tensor(0.0043, device='cuda:0')
29 tensor(0.0244, device='cuda:0')
30 tensor(0.6092, device='cuda:0')
31 tensor(8.4192, device='cuda:0')
32 tensor(2.8424, device='cuda:0')
33 tensor(6.5036, device='cuda:0')
34 tensor(0.9174, device='cuda:0')
35 tensor(14.5956, device='cuda:0')
36 tensor(45.3093, device='cuda:0')
37 tensor(13.9031, device='cuda:0')
38 tensor(13.0320, device='cuda:0')
39 tensor(0.0004, device='cuda:0')
40 tensor(4.9236, device='cuda:0')
41 tensor(9.5332, device='cuda:0')
42 tensor(0.0003, device='cuda:0')
43 tensor(5.7610, device='cuda:0')
44 tensor(4.2325, device='cuda:0')
45 tensor(4.1392, device='cuda:0')
46 tensor(0.0017, device='cuda:0')
47 tensor(1.5511, device='cuda:0')
48 tensor(0.0001, device='cuda:0')
49 tensor(0.1503, device='cuda:0')
50 tensor(3.6369, device='cuda:0')
51 tensor(14.8310, device='cuda:0')
52 tensor(1.6461, device='cuda:0')
53 tensor(0.1481, device='cuda:0')
54 tensor(4.7684e-06, device='cuda:0')
55 tensor(2.2855, device='cuda:0')
56 tensor(14.7752, device='cuda:0')
57 tensor(0.1075, device='cuda:0')
58 tensor(4.4197, device='cuda:0')
59 tensor(0.0241, device='cuda:0')
60 tensor(0.2129, device='cuda:0')
61 tensor(1.5020e-05, device='cuda:0')
62 tensor(0.8362, device='cuda:0')
63 tensor(1.4412, device='cuda:0')
64 tensor(1.9632, device='cuda:0')
65 tensor(8.5074, device='cuda:0')
66 tensor(10.0401, device='cuda:0')
67 tensor(2.3996, device='cuda:0')
68 tensor(7.9900, device='cuda:0')
69 tensor(1.5795, device='cuda:0')
70 tensor(5.1030, device='cuda:0')
71 tensor(0.0102, device='cuda:0')
72 tensor(0.8756, device='cuda:0')
73 tensor(0.0021, device='cuda:0')
74 tensor(4.5363, device='cuda:0')
75 tensor(2.4232, device='cuda:0')
76 tensor(0.0202, device='cuda:0')
77 tensor(1.9129, device='cuda:0')
78 tensor(0.7209, device='cuda:0')
79 tensor(1.3478, device='cuda:0')
80 tensor(0.0006, device='cuda:0')
81 tensor(1.7824, device='cuda:0')
82 tensor(0.9455, device='cuda:0')
83 tensor(9.9032, device='cuda:0')
84 tensor(1.3074, device='cuda:0')
85 tensor(0.1578, device='cuda:0')
86 tensor(7.8258, device='cuda:0')
87 tensor(0.3149, device='cuda:0')
88 tensor(6.8197, device='cuda:0')
89 tensor(1.6336, device='cuda:0')
90 tensor(0.5130, device='cuda:0')
91 tensor(6.0619, device='cuda:0')
92 tensor(0.0141, device='cuda:0')
93 tensor(0.3887, device='cuda:0')
94 tensor(5.4269, device='cuda:0')
95 tensor(12.9086, device='cuda:0')
96 tensor(4.7761, device='cuda:0')
97 tensor(12.5391, device='cuda:0')
98 tensor(4.2960, device='cuda:0')
99 tensor(2.0438, device='cuda:0')
100 tensor(26.4660, device='cuda:0')
101 tensor(15.6085, device='cuda:0')
102 tensor(3.7542, device='cuda:0')
103 tensor(1.5228, device='cuda:0')
104 tensor(1.3938, device='cuda:0')
105 tensor(2.2106, device='cuda:0')
106 tensor(0.6152, device='cuda:0')
107 tensor(12.8822, device='cuda:0')
108 tensor(0.1992, device='cuda:0')
109 tensor(0.7171, device='cuda:0')
110 tensor(0.2897, device='cuda:0')
111 tensor(5.0068e-06, device='cuda:0')
112 tensor(9.6606, device='cuda:0')
113 tensor(0.0596, device='cuda:0')
114 tensor(19.5023, device='cuda:0')
115 tensor(0.6806, device='cuda:0')
116 tensor(0.7316, device='cuda:0')
117 tensor(12.6233, device='cuda:0')
118 tensor(0.3050, device='cuda:0')
119 tensor(6.3182, device='cuda:0')
120 tensor(0.0003, device='cuda:0')
121 tensor(2.5006, device='cuda:0')
122 tensor(7.1526e-07, device='cuda:0')
123 tensor(6.3832, device='cuda:0')
124 tensor(8.7150, device='cuda:0')
125 tensor(14.9483, device='cuda:0')
126 tensor(0.0045, device='cuda:0')
127 tensor(0.7528, device='cuda:0')
128 tensor(5.0543e-05, device='cuda:0')
129 tensor(3.6423, device='cuda:0')
130 tensor(0.5134, device='cuda:0')
131 tensor(0.0673, device='cuda:0')
132 tensor(1.6212e-05, device='cuda:0')
133 tensor(0.7201, device='cuda:0')
134 tensor(3.1820, device='cuda:0')
135 tensor(4.1598, device='cuda:0')
136 tensor(8.5020, device='cuda:0')
137 tensor(0.0052, device='cuda:0')
138 tensor(7.5284, device='cuda:0')
139 tensor(1.7355, device='cuda:0')
140 tensor(0.6326, device='cuda:0')
141 tensor(0.0176, device='cuda:0')
142 tensor(3.0626, device='cuda:0')
143 tensor(0.1957, device='cuda:0')
144 tensor(0.4318, device='cuda:0')
145 tensor(0.0737, device='cuda:0')
146 tensor(3.4595, device='cuda:0')
147 tensor(8.3446e-07, device='cuda:0')
148 tensor(0.0037, device='cuda:0')
149 tensor(0.9618, device='cuda:0')
150 tensor(0.0314, device='cuda:0')
151 tensor(3.3346, device='cuda:0')
152 tensor(8.2254e-06, device='cuda:0')
153 tensor(0.2154, device='cuda:0')
154 tensor(4.2919, device='cuda:0')
155 tensor(0.0716, device='cuda:0')
156 tensor(0.4297, device='cuda:0')
157 tensor(0.3175, device='cuda:0')
158 tensor(1.1817, device='cuda:0')
159 tensor(3.5972, device='cuda:0')
160 tensor(0.0162, device='cuda:0')
161 tensor(2.5998, device='cuda:0')
162 tensor(0.0183, device='cuda:0')
163 tensor(3.5095, device='cuda:0')
164 tensor(9.7676, device='cuda:0')
165 tensor(0.1474, device='cuda:0')
166 tensor(21.4680, device='cuda:0')
167 tensor(9.0431, device='cuda:0')
168 tensor(0.0920, device='cuda:0')
169 tensor(10.6044, device='cuda:0')
170 tensor(6.2041, device='cuda:0')
171 tensor(1.6153, device='cuda:0')
172 tensor(8.5977, device='cuda:0')
173 tensor(4.3131, device='cuda:0')
174 tensor(16.7450, device='cuda:0')
175 tensor(1.8600, device='cuda:0')
176 tensor(0.0030, device='cuda:0')
177 tensor(0., device='cuda:0')
178 tensor(0.5775, device='cuda:0')
179 tensor(0.0068, device='cuda:0')
180 tensor(0.5546, device='cuda:0')
181 tensor(10.8156, device='cuda:0')
182 tensor(3.0108, device='cuda:0')
183 tensor(7.0565, device='cuda:0')
184 tensor(0.8754, device='cuda:0')
185 tensor(9.2842, device='cuda:0')
186 tensor(9.8514, device='cuda:0')
187 tensor(1.7004, device='cuda:0')
188 tensor(5.2212, device='cuda:0')
189 tensor(0.1376, device='cuda:0')
190 tensor(1.4494, device='cuda:0')
191 tensor(3.8080, device='cuda:0')
192 tensor(0.7230, device='cuda:0')
193 tensor(11.4573, device='cuda:0')
194 tensor(11.2928, device='cuda:0')
195 tensor(0.0383, device='cuda:0')
196 tensor(9.8343e-05, device='cuda:0')
197 tensor(17.5120, device='cuda:0')
198 tensor(0.1715, device='cuda:0')
199 tensor(3.8900, device='cuda:0')
200 tensor(1.3113e-06, device='cuda:0')
201 tensor(0.0443, device='cuda:0')
202 tensor(0.6600, device='cuda:0')
203 tensor(12.1071, device='cuda:0')
204 tensor(0.2034, device='cuda:0')
205 tensor(0.1036, device='cuda:0')
206 tensor(4.5960, device='cuda:0')
207 tensor(6.8670, device='cuda:0')
208 tensor(0.0912, device='cuda:0')
209 tensor(10.3238, device='cuda:0')
210 tensor(7.0304, device='cuda:0')
211 tensor(7.6930, device='cuda:0')
212 tensor(0.0562, device='cuda:0')
213 tensor(1.4952, device='cuda:0')
214 tensor(1.4543, device='cuda:0')
215 tensor(0.4733, device='cuda:0')
216 tensor(4.7684e-07, device='cuda:0')
217 tensor(0.1318, device='cuda:0')
218 tensor(4.3225, device='cuda:0')
219 tensor(4.0458, device='cuda:0')
220 tensor(0.9280, device='cuda:0')
221 tensor(14.8736, device='cuda:0')
222 tensor(0.0022, device='cuda:0')
223 tensor(4.8074, device='cuda:0')
224 tensor(0.0005, device='cuda:0')
225 tensor(2.3806, device='cuda:0')
226 tensor(5.9575, device='cuda:0')
227 tensor(2.2505, device='cuda:0')
228 tensor(0.2247, device='cuda:0')
229 tensor(16.5307, device='cuda:0')
230 tensor(3.9611, device='cuda:0')
231 tensor(0.6977, device='cuda:0')
232 tensor(0.0715, device='cuda:0')
233 tensor(8.8740, device='cuda:0')
234 tensor(10.0509, device='cuda:0')
235 tensor(0.0003, device='cuda:0')
236 tensor(4.4081, device='cuda:0')
237 tensor(0.1422, device='cuda:0')
238 tensor(0.1300, device='cuda:0')
239 tensor(14.2833, device='cuda:0')
240 tensor(22.7062, device='cuda:0')
241 tensor(3.0380, device='cuda:0')
242 tensor(0.5475, device='cuda:0')
243 tensor(0.0328, device='cuda:0')
244 tensor(6.7286, device='cuda:0')
245 tensor(0.0480, device='cuda:0')
246 tensor(20.2331, device='cuda:0')
247 tensor(0.9177, device='cuda:0')
248 tensor(0.0002, device='cuda:0')
249 tensor(19.5141, device='cuda:0')
250 tensor(0.4169, device='cuda:0')
251 tensor(5.8282, device='cuda:0')
252 tensor(1.1536, device='cuda:0')
253 tensor(1.2555, device='cuda:0')
254 tensor(3.6015, device='cuda:0')
255 tensor(11.9777, device='cuda:0')
256 tensor(12.3470, device='cuda:0')
257 tensor(8.2857, device='cuda:0')
258 tensor(10.6741, device='cuda:0')
259 tensor(1.2613, device='cuda:0')
260 tensor(5.3210, device='cuda:0')
261 tensor(3.7917, device='cuda:0')
262 tensor(0.0904, device='cuda:0')
263 tensor(0.6564, device='cuda:0')
264 tensor(3.8914, device='cuda:0')
265 tensor(2.8450, device='cuda:0')
266 tensor(5.6647, device='cuda:0')
267 tensor(3.5430, device='cuda:0')
268 tensor(0.1179, device='cuda:0')
269 tensor(5.6222, device='cuda:0')
270 tensor(3.5490, device='cuda:0')
271 tensor(0.2637, device='cuda:0')
272 tensor(7.7527, device='cuda:0')
273 tensor(0.0156, device='cuda:0')
274 tensor(1.6657, device='cuda:0')
275 tensor(0.0001, device='cuda:0')
276 tensor(0.0418, device='cuda:0')
277 tensor(0.1202, device='cuda:0')
278 tensor(0.0075, device='cuda:0')
279 tensor(12.1332, device='cuda:0')
280 tensor(11.3146, device='cuda:0')
281 tensor(4.7684e-07, device='cuda:0')
282 tensor(12.6365, device='cuda:0')
283 tensor(6.9157, device='cuda:0')
284 tensor(1.8928, device='cuda:0')
285 tensor(19.8445, device='cuda:0')
286 tensor(0.0379, device='cuda:0')
287 tensor(0.9857, device='cuda:0')
288 tensor(0.1137, device='cuda:0')
289 tensor(1.8548, device='cuda:0')
290 tensor(0.3658, device='cuda:0')
291 tensor(3.0141, device='cuda:0')
292 tensor(3.8632, device='cuda:0')
293 tensor(3.4689, device='cuda:0')
294 tensor(0.4702, device='cuda:0')
295 tensor(27.2123, device='cuda:0')
296 tensor(11.5580, device='cuda:0')
297 tensor(0.0917, device='cuda:0')
298 tensor(6.4358, device='cuda:0')
299 tensor(4.3741, device='cuda:0')
300 tensor(13.9540, device='cuda:0')
301 tensor(0.0431, device='cuda:0')
302 tensor(14.3536, device='cuda:0')
303 tensor(2.9311, device='cuda:0')
304 tensor(8.9877, device='cuda:0')
305 tensor(18.9544, device='cuda:0')
306 tensor(1.1205, device='cuda:0')
307 tensor(1.1568, device='cuda:0')
308 tensor(0.2700, device='cuda:0')
309 tensor(11.7060, device='cuda:0')
310 tensor(0.0003, device='cuda:0')
311 tensor(5.9708, device='cuda:0')
312 tensor(3.4580, device='cuda:0')
313 tensor(5.3285e-05, device='cuda:0')
314 tensor(3.6131, device='cuda:0')
315 tensor(3.6741, device='cuda:0')
316 tensor(0.0029, device='cuda:0')
317 tensor(0.0042, device='cuda:0')
318 tensor(0.1520, device='cuda:0')
319 tensor(2.8391, device='cuda:0')
320 tensor(6.0305, device='cuda:0')
321 tensor(5.5738, device='cuda:0')
322 tensor(1.6831, device='cuda:0')
323 tensor(1.7471, device='cuda:0')
324 tensor(3.2114, device='cuda:0')
325 tensor(5.5692, device='cuda:0')
326 tensor(0.0235, device='cuda:0')
327 tensor(9.3619, device='cuda:0')
328 tensor(2.0363, device='cuda:0')
329 tensor(5.0260, device='cuda:0')
330 tensor(15.5739, device='cuda:0')
331 tensor(0.1438, device='cuda:0')
332 tensor(5.8571, device='cuda:0')
333 tensor(1.3855, device='cuda:0')
334 tensor(3.7542, device='cuda:0')
335 tensor(0.9420, device='cuda:0')
336 tensor(7.0333e-06, device='cuda:0')
337 tensor(8.4397e-05, device='cuda:0')
338 tensor(0.3573, device='cuda:0')
339 tensor(0.1660, device='cuda:0')
340 tensor(0.0002, device='cuda:0')
341 tensor(9.0196, device='cuda:0')
342 tensor(6.8928, device='cuda:0')
343 tensor(6.7975, device='cuda:0')
344 tensor(7.6534, device='cuda:0')
345 tensor(3.9488, device='cuda:0')
346 tensor(5.3078, device='cuda:0')
347 tensor(0.0017, device='cuda:0')
348 tensor(1.1291, device='cuda:0')
349 tensor(0.0240, device='cuda:0')
350 tensor(0.2740, device='cuda:0')
351 tensor(18.6490, device='cuda:0')
352 tensor(0.3907, device='cuda:0')
353 tensor(13.9383, device='cuda:0')
354 tensor(0.1727, device='cuda:0')
355 tensor(1.2115, device='cuda:0')
356 tensor(3.1838, device='cuda:0')
357 tensor(13.0148, device='cuda:0')
358 tensor(0.0190, device='cuda:0')
359 tensor(1.1154, device='cuda:0')
360 tensor(9.8013, device='cuda:0')
361 tensor(6.1257, device='cuda:0')
362 tensor(18.7821, device='cuda:0')
363 tensor(2.3452, device='cuda:0')
364 tensor(0.6150, device='cuda:0')
365 tensor(4.5383, device='cuda:0')
366 tensor(0.5814, device='cuda:0')

# HIER einmal testen - predfilter einfügen zur auswertung am ende und earlystopping einbinden. Ach ebenso die folds auszulesen.

In [22]:
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
#pme hot encodings labels für skfold
y_labels = one_hot.argmax(axis=1)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_results = []

for fold_num, (train_idx, test_idx) in enumerate(skf.split(x_data, y_labels),start=1):
    print(f"Fold {fold_num}von 5")
    
    #split basierend auf cv skfold
    X_train_fold = x_data[train_idx]
    X_test_fold = x_data[test_idx]
    y_train_fold = one_hot[train_idx]
    y_test_fold = one_hot[test_idx]
    usage_test_fold = usage[test_idx]
    
    #standardisieren
    scaler = StandardScaler()
    X_train_fold = scaler.fit_transform(X_train_fold.reshape(X_train_fold.shape[0], -1)).reshape(X_train_fold.shape)
    X_test_fold = scaler.transform(X_test_fold.reshape(X_test_fold.shape[0], -1)).reshape(X_test_fold.shape) 
    
    #konvertieren zu tensoren
    x_train_tensor = torch.from_numpy(X_train_fold).float().unsqueeze(-1)
    y_train_tensor = torch.from_numpy(y_train_fold).float().argmax(axis=1)
    x_test_tensor = torch.from_numpy(X_test_fold).float().unsqueeze(-1)
    y_test_tensor = torch.from_numpy(y_test_fold).float().argmax(axis=1)
    
    #train und testset als datasets
    train_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(x_train_tensor, y_train_tensor), batch_size=batch_size, shuffle=True)
    test_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(x_test_tensor, y_test_tensor), batch_size=batch_size, shuffle=False)
    #model initialisiert, weights und lrscheduler
    model = FNO1d(modes, width, n_classes=n_classes).cuda()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=gamma)
    
    #early stopping
    patience = 30
    best_test_f1 = -np.inf
    patience_counter = 0
    best_model_state = None
    
    #Trainingsloop über trainingsdaten
    for ep in range(epochs):
        model.train()
        t1 = default_timer()
        train_cross_entropy = 0
        
        for x, y in train_loader:
            x, y = x.cuda(), y.cuda()
            optimizer.zero_grad()
            out = model(x)
            cross_entropy = F.cross_entropy(out, y)
            cross_entropy.backward()
            optimizer.step()
            train_cross_entropy += cross_entropy.item()
            acc_metric.update(out, y)
            f1_metric.update(out, y)
        
        epoch_acc = acc_metric.compute()
        epoch_f1 = f1_metric.compute()
        print(f"Epoch {ep+1}: Train Acc={epoch_acc:.4f}, F1={epoch_f1:.4f}")
        
        acc_metric.reset()
        f1_metric.reset()
        
        #testing loop
        scheduler.step()
        model.eval()
        test_cross_entropy = 0.0
        
        with torch.no_grad():
            for x, y in test_loader:
                x, y = x.cuda(), y.cuda()
                out = model(x)
                test_cross_entropy += F.cross_entropy(out, y).item()
                acc_metric.update(out, y)
                f1_metric.update(out, y)
        
        test_cross_entropy /= len(test_loader)
        epoch_acc = acc_metric.compute()
        epoch_f1 = f1_metric.compute()
        
        print(f"Test  Acc={epoch_acc:.4f}, F1={epoch_f1:.4f}")
        
        train_cross_entropy /= len(train_loader)
        t2 = default_timer()
        
        # Early Stopping
        if float(epoch_f1) > best_test_f1:
            best_test_f1 = float(epoch_f1)
            best_model_state = model.state_dict().copy()
            patience_counter = 0
            print(f"Neue beste F1: {best_test_f1:.4f}")
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"____Early Stop nach Epoch {ep+1}")
                if best_model_state is not None:
                    model.load_state_dict(best_model_state)
                break
        
        acc_metric.reset()
        f1_metric.reset()
    
    #Preidiction auf testset
    y_pred_fold = []
    model.eval()
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.cuda(), y.cuda()
            out = model(x)
            preds = out.argmax(dim=1).cpu().numpy()
            y_pred_fold.append(preds)
    
    y_pred_all = np.concatenate(y_pred_fold)
    y_test_all = y_test_tensor.cpu().numpy()
    
    fold_results.append({
        "fold": fold_num,
        "True_label": y_test_all,
        "Pred_label": y_pred_all,
        "workpiece_usage": usage_test_fold})
    
    print(f"Fold {fold_num} finished\n")

print("Results mit pred_filter")
fno_results = evaluate_folds(fold_results)
fno_results.to_csv('fno_torque-1D_results.csv', index=False)
fno_results

Fold 1von 5
Epoch 1: Train Acc=0.2639, F1=0.2641
Test  Acc=0.2503, F1=0.2154
Neue beste F1: 0.2154
Epoch 2: Train Acc=0.2993, F1=0.2945
Test  Acc=0.3108, F1=0.2923
Neue beste F1: 0.2923
Epoch 3: Train Acc=0.3250, F1=0.3211
Test  Acc=0.3363, F1=0.3072
Neue beste F1: 0.3072
Epoch 4: Train Acc=0.3539, F1=0.3505
Test  Acc=0.3612, F1=0.3321
Neue beste F1: 0.3321
Epoch 5: Train Acc=0.3746, F1=0.3697
Test  Acc=0.3468, F1=0.3208
Epoch 6: Train Acc=0.4026, F1=0.3985
Test  Acc=0.3735, F1=0.3506
Neue beste F1: 0.3506
Epoch 7: Train Acc=0.4138, F1=0.4096
Test  Acc=0.3925, F1=0.3801
Neue beste F1: 0.3801
Epoch 8: Train Acc=0.4343, F1=0.4312
Test  Acc=0.4107, F1=0.3945
Neue beste F1: 0.3945
Epoch 9: Train Acc=0.4566, F1=0.4539
Test  Acc=0.3755, F1=0.3705
Epoch 10: Train Acc=0.4828, F1=0.4809
Test  Acc=0.4135, F1=0.4006
Neue beste F1: 0.4006
Epoch 11: Train Acc=0.5110, F1=0.5096
Test  Acc=0.3968, F1=0.3806
Epoch 12: Train Acc=0.5431, F1=0.5422
Test  Acc=0.3980, F1=0.3947
Epoch 13: Train Acc=0.5732, F1=0.5722
Test  Acc=0.3915, F1=0.3878
Epoch 14: Train Acc=0.6131, F1=0.6122
Test  Acc=0.3913, F1=0.3921
Epoch 15: Train Acc=0.6513, F1=0.6509
Test  Acc=0.3855, F1=0.3825
Epoch 16: Train Acc=0.6840, F1=0.6841
Test  Acc=0.3790, F1=0.3795
Epoch 17: Train Acc=0.7201, F1=0.7198
Test  Acc=0.3745, F1=0.3765
Epoch 18: Train Acc=0.7550, F1=0.7548
Test  Acc=0.3877, F1=0.3912
Epoch 19: Train Acc=0.7839, F1=0.7841
Test  Acc=0.3817, F1=0.3806
Epoch 20: Train Acc=0.8138, F1=0.8137
Test  Acc=0.3823, F1=0.3848
Epoch 21: Train Acc=0.8374, F1=0.8379
Test  Acc=0.3805, F1=0.3798
Epoch 22: Train Acc=0.8575, F1=0.8579
Test  Acc=0.3770, F1=0.3696
Epoch 23: Train Acc=0.8713, F1=0.8714
Test  Acc=0.3808, F1=0.3816
Epoch 24: Train Acc=0.8923, F1=0.8921
Test  Acc=0.3725, F1=0.3754
Epoch 25: Train Acc=0.8937, F1=0.8937
Test  Acc=0.3808, F1=0.3787
Epoch 26: Train Acc=0.9054, F1=0.9055
Test  Acc=0.3690, F1=0.3692
Epoch 27: Train Acc=0.9174, F1=0.9170
Test  Acc=0.3708, F1=0.3723
Epoch 28: Train Acc=0.9183, F1=0.9186
Test  Acc=0.3835, F1=0.3836
Epoch 29: Train Acc=0.9259, F1=0.9261
Test  Acc=0.3708, F1=0.3708
Epoch 30: Train Acc=0.9351, F1=0.9354
Test  Acc=0.3910, F1=0.3897
Epoch 31: Train Acc=0.9289, F1=0.9291
Test  Acc=0.3643, F1=0.3640
Epoch 32: Train Acc=0.9471, F1=0.9472
Test  Acc=0.3733, F1=0.3725
Epoch 33: Train Acc=0.9372, F1=0.9373
Test  Acc=0.3750, F1=0.3778
Epoch 34: Train Acc=0.9372, F1=0.9369
Test  Acc=0.3757, F1=0.3798
Epoch 35: Train Acc=0.9479, F1=0.9478
Test  Acc=0.3775, F1=0.3781
Epoch 36: Train Acc=0.9516, F1=0.9516
Test  Acc=0.3627, F1=0.3660
Epoch 37: Train Acc=0.9436, F1=0.9439
Test  Acc=0.3750, F1=0.3747
Epoch 38: Train Acc=0.9512, F1=0.9512
Test  Acc=0.3792, F1=0.3803
Epoch 39: Train Acc=0.9536, F1=0.9535
Test  Acc=0.3770, F1=0.3779
Epoch 40: Train Acc=0.9496, F1=0.9497
Test  Acc=0.3680, F1=0.3706
____Early Stop nach Epoch 40
Fold 1 finished

Fold 2von 5
Epoch 1: Train Acc=0.2615, F1=0.2601
Test  Acc=0.2915, F1=0.2522
Neue beste F1: 0.2522
Epoch 2: Train Acc=0.3064, F1=0.3067
Test  Acc=0.2977, F1=0.2818
Neue beste F1: 0.2818
Epoch 3: Train Acc=0.3289, F1=0.3220
Test  Acc=0.3325, F1=0.3182
Neue beste F1: 0.3182
Epoch 4: Train Acc=0.3590, F1=0.3557
Test  Acc=0.3495, F1=0.3405
Neue beste F1: 0.3405
Epoch 5: Train Acc=0.3831, F1=0.3826
Test  Acc=0.3978, F1=0.3817
Neue beste F1: 0.3817
Epoch 6: Train Acc=0.4072, F1=0.4044
Test  Acc=0.3855, F1=0.3667
Epoch 7: Train Acc=0.4231, F1=0.4198
Test  Acc=0.3802, F1=0.3654
Epoch 8: Train Acc=0.4471, F1=0.4442
Test  Acc=0.4013, F1=0.3810
Epoch 9: Train Acc=0.4609, F1=0.4567
Test  Acc=0.4045, F1=0.3930
Neue beste F1: 0.3930
Epoch 10: Train Acc=0.4777, F1=0.4745
Test  Acc=0.4003, F1=0.4012
Neue beste F1: 0.4012
Epoch 11: Train Acc=0.5100, F1=0.5079
Test  Acc=0.4013, F1=0.3868
Epoch 12: Train Acc=0.5297, F1=0.5275
Test  Acc=0.3930, F1=0.3956
Epoch 13: Train Acc=0.5577, F1=0.5563
Test  Acc=0.3930, F1=0.3833
Epoch 14: Train Acc=0.5839, F1=0.5812
Test  Acc=0.4030, F1=0.3957
Epoch 15: Train Acc=0.6161, F1=0.6139
Test  Acc=0.3952, F1=0.3947
Epoch 16: Train Acc=0.6472, F1=0.6470
Test  Acc=0.4020, F1=0.4025
Neue beste F1: 0.4025
Epoch 17: Train Acc=0.6852, F1=0.6842
Test  Acc=0.3913, F1=0.3897
Epoch 18: Train Acc=0.7147, F1=0.7147
Test  Acc=0.3860, F1=0.3630
Epoch 19: Train Acc=0.7367, F1=0.7362
Test  Acc=0.3882, F1=0.3866
Epoch 20: Train Acc=0.7798, F1=0.7800
Test  Acc=0.3815, F1=0.3705
Epoch 21: Train Acc=0.8026, F1=0.8030
Test  Acc=0.3748, F1=0.3725
Epoch 22: Train Acc=0.8288, F1=0.8292
Test  Acc=0.3865, F1=0.3820
Epoch 23: Train Acc=0.8435, F1=0.8437
Test  Acc=0.3970, F1=0.3939
Epoch 24: Train Acc=0.8644, F1=0.8647
Test  Acc=0.3882, F1=0.3842
Epoch 25: Train Acc=0.8819, F1=0.8817
Test  Acc=0.3912, F1=0.3864
Epoch 26: Train Acc=0.8924, F1=0.8930
Test  Acc=0.3875, F1=0.3819
Epoch 27: Train Acc=0.9029, F1=0.9031
Test  Acc=0.3832, F1=0.3782
Epoch 28: Train Acc=0.9043, F1=0.9044
Test  Acc=0.3912, F1=0.3929
Epoch 29: Train Acc=0.9161, F1=0.9162
Test  Acc=0.3830, F1=0.3806
Epoch 30: Train Acc=0.9295, F1=0.9296
Test  Acc=0.3875, F1=0.3869
Epoch 31: Train Acc=0.9222, F1=0.9228
Test  Acc=0.3748, F1=0.3773
Epoch 32: Train Acc=0.9266, F1=0.9268
Test  Acc=0.3767, F1=0.3746
Epoch 33: Train Acc=0.9379, F1=0.9381
Test  Acc=0.3803, F1=0.3753
Epoch 34: Train Acc=0.9310, F1=0.9310
Test  Acc=0.3755, F1=0.3743
Epoch 35: Train Acc=0.9467, F1=0.9468
Test  Acc=0.3827, F1=0.3818
Epoch 36: Train Acc=0.9402, F1=0.9401
Test  Acc=0.3815, F1=0.3802
Epoch 37: Train Acc=0.9364, F1=0.9368
Test  Acc=0.3923, F1=0.3938
Epoch 38: Train Acc=0.9474, F1=0.9475
Test  Acc=0.3720, F1=0.3665
Epoch 39: Train Acc=0.9478, F1=0.9478
Test  Acc=0.3828, F1=0.3792
Epoch 40: Train Acc=0.9549, F1=0.9552
Test  Acc=0.3760, F1=0.3706
Epoch 41: Train Acc=0.9466, F1=0.9464
Test  Acc=0.3990, F1=0.3950
Epoch 42: Train Acc=0.9554, F1=0.9557
Test  Acc=0.3665, F1=0.3669
Epoch 43: Train Acc=0.9494, F1=0.9497
Test  Acc=0.3867, F1=0.3865
Epoch 44: Train Acc=0.9608, F1=0.9608
Test  Acc=0.3708, F1=0.3667
Epoch 45: Train Acc=0.9490, F1=0.9494
Test  Acc=0.3800, F1=0.3794
Epoch 46: Train Acc=0.9647, F1=0.9650
Test  Acc=0.3702, F1=0.3716
____Early Stop nach Epoch 46
Fold 2 finished

Fold 3von 5
Epoch 1: Train Acc=0.2634, F1=0.2648
Test  Acc=0.2637, F1=0.2508
Neue beste F1: 0.2508
Epoch 2: Train Acc=0.3019, F1=0.2962
Test  Acc=0.3257, F1=0.3142
Neue beste F1: 0.3142
Epoch 3: Train Acc=0.3384, F1=0.3361
Test  Acc=0.3343, F1=0.3029
Epoch 4: Train Acc=0.3649, F1=0.3624
Test  Acc=0.3777, F1=0.3661
Neue beste F1: 0.3661
Epoch 5: Train Acc=0.3903, F1=0.3880
Test  Acc=0.3733, F1=0.3514
Epoch 6: Train Acc=0.4054, F1=0.4023
Test  Acc=0.3963, F1=0.3730
Neue beste F1: 0.3730
Epoch 7: Train Acc=0.4293, F1=0.4251
Test  Acc=0.4100, F1=0.3799
Neue beste F1: 0.3799
Epoch 8: Train Acc=0.4533, F1=0.4505
Test  Acc=0.4060, F1=0.3867
Neue beste F1: 0.3867
Epoch 9: Train Acc=0.4651, F1=0.4608
Test  Acc=0.3853, F1=0.3746
Epoch 10: Train Acc=0.4787, F1=0.4756
Test  Acc=0.3970, F1=0.3907
Neue beste F1: 0.3907
Epoch 11: Train Acc=0.5102, F1=0.5064
Test  Acc=0.4020, F1=0.3947
Neue beste F1: 0.3947
Epoch 12: Train Acc=0.5356, F1=0.5333
Test  Acc=0.4000, F1=0.3922
Epoch 13: Train Acc=0.5661, F1=0.5641
Test  Acc=0.4118, F1=0.4047
Neue beste F1: 0.4047
Epoch 14: Train Acc=0.5936, F1=0.5919
Test  Acc=0.4022, F1=0.3921
Epoch 15: Train Acc=0.6278, F1=0.6268
Test  Acc=0.3815, F1=0.3729
Epoch 16: Train Acc=0.6639, F1=0.6618
Test  Acc=0.4007, F1=0.3880
Epoch 17: Train Acc=0.6946, F1=0.6931
Test  Acc=0.3918, F1=0.3918
Epoch 18: Train Acc=0.7303, F1=0.7299
Test  Acc=0.3870, F1=0.3723
Epoch 19: Train Acc=0.7631, F1=0.7620
Test  Acc=0.3955, F1=0.3885
Epoch 20: Train Acc=0.7906, F1=0.7898
Test  Acc=0.3643, F1=0.3632
Epoch 21: Train Acc=0.8174, F1=0.8174
Test  Acc=0.3792, F1=0.3789
Epoch 22: Train Acc=0.8320, F1=0.8324
Test  Acc=0.3817, F1=0.3838
Epoch 23: Train Acc=0.8493, F1=0.8497
Test  Acc=0.3810, F1=0.3809
Epoch 24: Train Acc=0.8699, F1=0.8699
Test  Acc=0.3892, F1=0.3831
Epoch 25: Train Acc=0.8777, F1=0.8784
Test  Acc=0.3860, F1=0.3849
Epoch 26: Train Acc=0.9005, F1=0.9010
Test  Acc=0.3857, F1=0.3817
Epoch 27: Train Acc=0.9097, F1=0.9095
Test  Acc=0.3920, F1=0.3896
Epoch 28: Train Acc=0.9059, F1=0.9064
Test  Acc=0.3762, F1=0.3765
Epoch 29: Train Acc=0.9194, F1=0.9193
Test  Acc=0.3960, F1=0.3908
Epoch 30: Train Acc=0.9244, F1=0.9245
Test  Acc=0.3775, F1=0.3716
Epoch 31: Train Acc=0.9317, F1=0.9323
Test  Acc=0.3898, F1=0.3842
Epoch 32: Train Acc=0.9384, F1=0.9386
Test  Acc=0.3795, F1=0.3811
Epoch 33: Train Acc=0.9444, F1=0.9446
Test  Acc=0.3813, F1=0.3801
Epoch 34: Train Acc=0.9349, F1=0.9350
Test  Acc=0.3905, F1=0.3827
Epoch 35: Train Acc=0.9390, F1=0.9391
Test  Acc=0.3755, F1=0.3701
Epoch 36: Train Acc=0.9441, F1=0.9443
Test  Acc=0.3795, F1=0.3783
Epoch 37: Train Acc=0.9523, F1=0.9521
Test  Acc=0.3643, F1=0.3632
Epoch 38: Train Acc=0.9511, F1=0.9510
Test  Acc=0.3708, F1=0.3678
Epoch 39: Train Acc=0.9492, F1=0.9495
Test  Acc=0.3672, F1=0.3622
Epoch 40: Train Acc=0.9511, F1=0.9512
Test  Acc=0.3635, F1=0.3608
Epoch 41: Train Acc=0.9438, F1=0.9438
Test  Acc=0.3738, F1=0.3719
Epoch 42: Train Acc=0.9592, F1=0.9593
Test  Acc=0.3855, F1=0.3824
Epoch 43: Train Acc=0.9614, F1=0.9614
Test  Acc=0.3805, F1=0.3787
____Early Stop nach Epoch 43
Fold 3 finished

Fold 4von 5
Epoch 1: Train Acc=0.2616, F1=0.2586
Test  Acc=0.2955, F1=0.2767
Neue beste F1: 0.2767
Epoch 2: Train Acc=0.3070, F1=0.3033
Test  Acc=0.3133, F1=0.2766
Epoch 3: Train Acc=0.3320, F1=0.3263
Test  Acc=0.3410, F1=0.3287
Neue beste F1: 0.3287
Epoch 4: Train Acc=0.3619, F1=0.3586
Test  Acc=0.3740, F1=0.3623
Neue beste F1: 0.3623
Epoch 5: Train Acc=0.3849, F1=0.3802
Test  Acc=0.3732, F1=0.3706
Neue beste F1: 0.3706
Epoch 6: Train Acc=0.4064, F1=0.4030
Test  Acc=0.3960, F1=0.3946
Neue beste F1: 0.3946
Epoch 7: Train Acc=0.4275, F1=0.4244
Test  Acc=0.3997, F1=0.3908
Epoch 8: Train Acc=0.4468, F1=0.4429
Test  Acc=0.4058, F1=0.3836
Epoch 9: Train Acc=0.4634, F1=0.4604
Test  Acc=0.4013, F1=0.3791
Epoch 10: Train Acc=0.4824, F1=0.4791
Test  Acc=0.3800, F1=0.3767
Epoch 11: Train Acc=0.5145, F1=0.5126
Test  Acc=0.3830, F1=0.3625
Epoch 12: Train Acc=0.5353, F1=0.5334
Test  Acc=0.3902, F1=0.3876
Epoch 13: Train Acc=0.5685, F1=0.5675
Test  Acc=0.4210, F1=0.4058
Neue beste F1: 0.4058
Epoch 14: Train Acc=0.5972, F1=0.5961
Test  Acc=0.3795, F1=0.3787
Epoch 15: Train Acc=0.6335, F1=0.6330
Test  Acc=0.4007, F1=0.3975
Epoch 16: Train Acc=0.6686, F1=0.6684
Test  Acc=0.3842, F1=0.3822
Epoch 17: Train Acc=0.7048, F1=0.7048
Test  Acc=0.3685, F1=0.3671
Epoch 18: Train Acc=0.7410, F1=0.7420
Test  Acc=0.3760, F1=0.3740
Epoch 19: Train Acc=0.7690, F1=0.7682
Test  Acc=0.3808, F1=0.3826
Epoch 20: Train Acc=0.8033, F1=0.8030
Test  Acc=0.3885, F1=0.3895
Epoch 21: Train Acc=0.8250, F1=0.8249
Test  Acc=0.3852, F1=0.3808
Epoch 22: Train Acc=0.8504, F1=0.8507
Test  Acc=0.3882, F1=0.3887
Epoch 23: Train Acc=0.8659, F1=0.8661
Test  Acc=0.3732, F1=0.3720
Epoch 24: Train Acc=0.8830, F1=0.8833
Test  Acc=0.3720, F1=0.3726
Epoch 25: Train Acc=0.8963, F1=0.8967
Test  Acc=0.3753, F1=0.3692
Epoch 26: Train Acc=0.9043, F1=0.9044
Test  Acc=0.3690, F1=0.3687
Epoch 27: Train Acc=0.9050, F1=0.9050
Test  Acc=0.3742, F1=0.3684
Epoch 28: Train Acc=0.9207, F1=0.9213
Test  Acc=0.3755, F1=0.3720
Epoch 29: Train Acc=0.9304, F1=0.9307
Test  Acc=0.3850, F1=0.3819
Epoch 30: Train Acc=0.9242, F1=0.9247
Test  Acc=0.3650, F1=0.3599
Epoch 31: Train Acc=0.9320, F1=0.9321
Test  Acc=0.3808, F1=0.3805
Epoch 32: Train Acc=0.9401, F1=0.9400
Test  Acc=0.3645, F1=0.3637
Epoch 33: Train Acc=0.9321, F1=0.9324
Test  Acc=0.3670, F1=0.3698
Epoch 34: Train Acc=0.9444, F1=0.9443
Test  Acc=0.3670, F1=0.3648
Epoch 35: Train Acc=0.9485, F1=0.9485
Test  Acc=0.3742, F1=0.3742
Epoch 36: Train Acc=0.9414, F1=0.9414
Test  Acc=0.3690, F1=0.3681
Epoch 37: Train Acc=0.9460, F1=0.9462
Test  Acc=0.3650, F1=0.3681
Epoch 38: Train Acc=0.9526, F1=0.9526
Test  Acc=0.3742, F1=0.3702
Epoch 39: Train Acc=0.9544, F1=0.9545
Test  Acc=0.3765, F1=0.3715
Epoch 40: Train Acc=0.9496, F1=0.9498
Test  Acc=0.3650, F1=0.3614
Epoch 41: Train Acc=0.9455, F1=0.9456
Test  Acc=0.3680, F1=0.3670
Epoch 42: Train Acc=0.9576, F1=0.9578
Test  Acc=0.3663, F1=0.3656
Epoch 43: Train Acc=0.9556, F1=0.9557
Test  Acc=0.3677, F1=0.3695
____Early Stop nach Epoch 43
Fold 4 finished

Fold 5von 5
Epoch 1: Train Acc=0.2617, F1=0.2579
Test  Acc=0.2743, F1=0.2370
Neue beste F1: 0.2370
Epoch 2: Train Acc=0.3098, F1=0.3066
Test  Acc=0.3092, F1=0.2657
Neue beste F1: 0.2657
Epoch 3: Train Acc=0.3326, F1=0.3291
Test  Acc=0.3505, F1=0.3265
Neue beste F1: 0.3265
Epoch 4: Train Acc=0.3499, F1=0.3429
Test  Acc=0.3408, F1=0.3369
Neue beste F1: 0.3369
Epoch 5: Train Acc=0.3696, F1=0.3674
Test  Acc=0.3647, F1=0.3578
Neue beste F1: 0.3578
Epoch 6: Train Acc=0.3987, F1=0.3979
Test  Acc=0.3918, F1=0.3788
Neue beste F1: 0.3788
Epoch 7: Train Acc=0.4099, F1=0.4086
Test  Acc=0.3982, F1=0.3772
Epoch 8: Train Acc=0.4311, F1=0.4283
Test  Acc=0.4002, F1=0.3899
Neue beste F1: 0.3899
Epoch 9: Train Acc=0.4451, F1=0.4423
Test  Acc=0.4030, F1=0.3871
Epoch 10: Train Acc=0.4641, F1=0.4631
Test  Acc=0.3988, F1=0.3714
Epoch 11: Train Acc=0.4864, F1=0.4847
Test  Acc=0.3855, F1=0.3814
Epoch 12: Train Acc=0.5118, F1=0.5110
Test  Acc=0.4153, F1=0.4031
Neue beste F1: 0.4031
Epoch 13: Train Acc=0.5348, F1=0.5340
Test  Acc=0.3715, F1=0.3684
Epoch 14: Train Acc=0.5662, F1=0.5663
Test  Acc=0.4047, F1=0.3950
Epoch 15: Train Acc=0.5918, F1=0.5920
Test  Acc=0.4007, F1=0.3842
Epoch 16: Train Acc=0.6326, F1=0.6330
Test  Acc=0.3900, F1=0.3894
Epoch 17: Train Acc=0.6597, F1=0.6602
Test  Acc=0.4197, F1=0.4163
Neue beste F1: 0.4163
Epoch 18: Train Acc=0.6889, F1=0.6889
Test  Acc=0.3733, F1=0.3595
Epoch 19: Train Acc=0.7166, F1=0.7177
Test  Acc=0.3950, F1=0.3915
Epoch 20: Train Acc=0.7501, F1=0.7506
Test  Acc=0.3848, F1=0.3841
Epoch 21: Train Acc=0.7800, F1=0.7806
Test  Acc=0.3810, F1=0.3785
Epoch 22: Train Acc=0.8053, F1=0.8057
Test  Acc=0.3932, F1=0.3899
Epoch 23: Train Acc=0.8243, F1=0.8247
Test  Acc=0.3957, F1=0.3940
Epoch 24: Train Acc=0.8459, F1=0.8459
Test  Acc=0.3640, F1=0.3633
Epoch 25: Train Acc=0.8593, F1=0.8594
Test  Acc=0.3823, F1=0.3750
Epoch 26: Train Acc=0.8726, F1=0.8730
Test  Acc=0.3915, F1=0.3911
Epoch 27: Train Acc=0.8899, F1=0.8903
Test  Acc=0.3708, F1=0.3723
Epoch 28: Train Acc=0.8993, F1=0.8994
Test  Acc=0.3868, F1=0.3829
Epoch 29: Train Acc=0.9139, F1=0.9144
Test  Acc=0.3842, F1=0.3768
Epoch 30: Train Acc=0.9119, F1=0.9119
Test  Acc=0.3795, F1=0.3772
Epoch 31: Train Acc=0.9204, F1=0.9213
Test  Acc=0.3650, F1=0.3627
Epoch 32: Train Acc=0.9212, F1=0.9216
Test  Acc=0.3562, F1=0.3573
Epoch 33: Train Acc=0.9385, F1=0.9387
Test  Acc=0.3760, F1=0.3751
Epoch 34: Train Acc=0.9270, F1=0.9272
Test  Acc=0.3635, F1=0.3598
Epoch 35: Train Acc=0.9387, F1=0.9389
Test  Acc=0.3570, F1=0.3574
Epoch 36: Train Acc=0.9435, F1=0.9437
Test  Acc=0.3548, F1=0.3540
Epoch 37: Train Acc=0.9194, F1=0.9201
Test  Acc=0.3808, F1=0.3785
Epoch 38: Train Acc=0.9469, F1=0.9472
Test  Acc=0.3700, F1=0.3637
Epoch 39: Train Acc=0.9459, F1=0.9461
Test  Acc=0.3770, F1=0.3766
Epoch 40: Train Acc=0.9361, F1=0.9364
Test  Acc=0.3668, F1=0.3619
Epoch 41: Train Acc=0.9497, F1=0.9499
Test  Acc=0.3685, F1=0.3698
Epoch 42: Train Acc=0.9504, F1=0.9507
Test  Acc=0.3593, F1=0.3622
Epoch 43: Train Acc=0.9507, F1=0.9508
Test  Acc=0.3787, F1=0.3779
Epoch 44: Train Acc=0.9561, F1=0.9562
Test  Acc=0.3512, F1=0.3535
Epoch 45: Train Acc=0.9508, F1=0.9509
Test  Acc=0.3695, F1=0.3698
Epoch 46: Train Acc=0.9444, F1=0.9444
Test  Acc=0.3805, F1=0.3760
Epoch 47: Train Acc=0.9669, F1=0.9671
Test  Acc=0.3767, F1=0.3769
____Early Stop nach Epoch 47
Fold 5 finished

Results mit pred_filter

,Labelstrategie,Accuracy_mean,Accuracy_std,Precision_mean,Precision_std,Recall_mean,Recall_std,F1_macro_mean,F1_macro_std
0,Binary_s1st,82.043868,0.023635,89.227871,0.034242,88.195785,0.022738,88.648260,0.016705
1,Binary_all,78.288000,0.006652,87.448221,0.004416,85.080000,0.013132,86.239649,0.005414
2,Single_s1st,45.306829,0.045998,45.086812,0.029398,42.075756,0.045765,40.178225,0.038506
3,Single_all,39.664000,0.004298,37.823245,0.003719,37.265000,0.005096,37.346859,0.003675
4,Grouped_s1st,55.893390,0.035638,56.721026,0.028814,55.991851,0.043483,55.026169,0.036279
5,Grouped_all,49.744000,0.005838,49.790709,0.004131,49.744000,0.005838,49.644311,0.005121

FNO with features of tsfresh

In [27]:
df_tsfresh = data_v2_df.copy()
if "id" not in df_tsfresh.columns:
    df_tsfresh = data_v2_df.reset_index().rename(columns={"index": "id"})
df_tsfresh.head()

,id,time_values,torque_values,angle_values,gradient_values,step_values,class_values,workpiece_location,workpiece_usage,workpiece_result,scenario_condition,scenario_exception
0,0,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[0.067, 0.077, 0.126, 0.087, 0.089, 0.097, 0.0...","[0.5, 1.25, 2.25, 3.75, 5.0, 6.25, 7.5, 8.75, ...","[0.0, 0.0, 0.0298, 0.0214, 0.0064, 0.0023, -0....","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,left,0,OK,normal,0
1,1,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[-0.005, 0.008, 0.061, 0.069, 0.104, 0.124, 0....","[0.0, 0.25, 0.75, 1.5, 2.5, 4.0, 5.25, 6.5, 7....","[0.0, 0.0, 0.0, 0.0, 0.0287, 0.0282, 0.0091, 0...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,right,0,OK,normal,0
2,2,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[-0.003, 0.01, 0.039, 0.099, 0.102, 0.087, 0.0...","[0.0, 0.5, 1.25, 2.25, 3.5, 4.75, 6.0, 7.5, 8....","[0.0, 0.0, 0.0, 0.0196, 0.0223, 0.0211, 0.0096...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,left,1,OK,normal,0
3,3,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[0.081, 0.059, 0.12, 0.077, 0.043, 0.059, 0.06...","[0.75, 1.75, 2.75, 4.0, 5.25, 6.5, 7.75, 9.25,...","[0.0, 0.0, 0.0261, 0.0207, 0.0, -0.0036, -0.00...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,right,1,OK,normal,0
4,4,"[0.0, 0.0012, 0.0024, 0.0036, 0.0048, 0.006, 0...","[-0.003, -0.0012, 0.0006, 0.0024, 0.0042, 0.00...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 1.5, 2.5, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.025...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",001_control-group,left,2,OK,normal,0

In [28]:
torque_values = df_tsfresh["torque_values"]
time_values = df_tsfresh["time_values"]
screw_id = df_tsfresh["id"]
y_labels = df_tsfresh["class_values"]

df_long = df_tsfresh.explode('torque_values').reset_index(drop=True)
df_long['time_values'] = df_long.groupby('id').cumcount()
df_long = df_long[['id', 'time_values', 'torque_values']]

df_long['torque_values'] = pd.to_numeric(df_long['torque_values'])
df_long['time_values'] = pd.to_numeric(df_long['time_values']) 
print(df_long.shape) #12500 x 800 = 10mil
df_long.head()

(10000000, 3)

   id  time_values  torque_values
0   0            0          0.067
1   0            1          0.077
2   0            2          0.126
3   0            3          0.087
4   0            4          0.089

In [22]:
print(df_long['time_values'].max())
print(df_long['time_values'].count())

799
10000000

In [23]:
from tsfresh import extract_features, select_features
from tsfresh.utilities.dataframe_functions import impute

X_extr_feat = extract_features(df_long, column_id='id', column_sort='time_values', column_value='torque_values')
impute(X_extr_feat)
y = df_tsfresh.set_index("id")["class_values"]
X_selected = select_features(X_extr_feat,y)

Feature Extraction: 100%|██████████| 30/30 [14:47<00:00, 29.57s/it]
c:\Users\Patrick\miniconda3\envs\thesis_gpu\Lib\site-packages\tsfresh\utilities\dataframe_functions.py:198: RuntimeWarning: The columns ['torque_values__query_similarity_count__query_None__threshold_0.0'] did not have any finite values. Filling with zeros.
  warnings.warn(

In [35]:
#speichern mit pickle
import pickle
with open('X_selected_tsfresh.pickle','wb') as f:
    pickle.dump(X_selected, f, pickle.HIGHEST_PROTOCOL)
y_tsfresh = y.copy()
with open('y_tsfresh.pickle','wb') as f:
    pickle.dump(y_tsfresh, f, pickle.HIGHEST_PROTOCOL)

In [40]:
#laden mit pickle
"""with open('X_selected_tsfresh.pickle', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    data = pickle.load(f)"""
    
import pickle   
with open('X_selected_tsfresh.pickle', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    x_tsfresh = pickle.load(f)
with open('y_tsfresh.pickle', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    y_tsfresh = pickle.load(f)
print(x_tsfresh.shape)
print(y_tsfresh.shape)
print(y_tsfresh[0])

(12500, 705)
(12500,)
001_control-group

In [42]:
print(x_tsfresh.shape) #macht dann doch gar keinen sinn mehr da keine sequenz mehr sondern einzelne features je sample/screw

(12500, 705)

In [ ]:
print(X_selected.columns[X_selected.isna().all()].tolist())
zero_cols = X_selected.columns[(X_selected == 0).all()].tolist()
print(zero_cols)

[]
[]

In [45]:
from sklearn.preprocessing import LabelEncoder
X = x_tsfresh.to_numpy(dtype=np.float32)
le = LabelEncoder()
y = le.fit_transform(y_tsfresh)


n_classes_tsfresh = len(np.unique(y))

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_results_tsfresh = []

for fold_num, (train_idx, test_idx) in enumerate(skf.split(X, y), start=1):
    print(f"Fold {fold_num} von 5")

    X_train_fold = X[train_idx]
    X_test_fold = X[test_idx]
    y_train_fold = y[train_idx]
    y_test_fold = y[test_idx]

    scaler = StandardScaler()
    X_train_fold = scaler.fit_transform(X_train_fold)
    X_test_fold = scaler.transform(X_test_fold)

    x_train_tensor = torch.from_numpy(X_train_fold).float().unsqueeze(-1)
    y_train_tensor = torch.from_numpy(y_train_fold).long()

    x_test_tensor = torch.from_numpy(X_test_fold).float().unsqueeze(-1)
    y_test_tensor = torch.from_numpy(y_test_fold).long()

    train_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x_train_tensor, y_train_tensor),
        batch_size=batch_size,
        shuffle=True
    )
    test_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x_test_tensor, y_test_tensor),
        batch_size=batch_size,
        shuffle=False
    )

    model = FNO1d(modes, width, n_classes=n_classes_tsfresh).cuda()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=gamma)

    patience = 30
    best_test_f1 = -np.inf
    patience_counter = 0
    best_model_state = None

    for ep in range(epochs):
        model.train()
        train_cross_entropy = 0.0

        for x, y_batch in train_loader:
            x, y_batch = x.cuda(), y_batch.cuda()
            optimizer.zero_grad()
            out = model(x)
            loss = F.cross_entropy(out, y_batch)
            loss.backward()
            optimizer.step()

            train_cross_entropy += loss.item()
            acc_metric.update(out, y_batch)
            f1_metric.update(out, y_batch)

        epoch_acc = acc_metric.compute()
        epoch_f1 = f1_metric.compute()
        acc_metric.reset()
        f1_metric.reset()

        scheduler.step()
        model.eval()
        test_cross_entropy = 0.0

        with torch.no_grad():
            for x, y_batch in test_loader:
                x, y_batch = x.cuda(), y_batch.cuda()
                out = model(x)
                test_cross_entropy += F.cross_entropy(out, y_batch).item()
                acc_metric.update(out, y_batch)
                f1_metric.update(out, y_batch)

        test_cross_entropy /= len(test_loader)
        epoch_acc = acc_metric.compute()
        epoch_f1 = f1_metric.compute()
        acc_metric.reset()
        f1_metric.reset()

        if float(epoch_f1) > best_test_f1:
            best_test_f1 = float(epoch_f1)
            best_model_state = model.state_dict().copy()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                if best_model_state is not None:
                    model.load_state_dict(best_model_state)
                break

    y_pred_fold = []
    model.eval()
    with torch.no_grad():
        for x, _ in test_loader:
            x = x.cuda()
            out = model(x)
            y_pred_fold.append(out.argmax(dim=1).cpu().numpy())

    y_pred_all = np.concatenate(y_pred_fold)

    fold_results_tsfresh.append({
        "fold": fold_num,
        "True_label": y_test_fold,
        "Pred_label": y_pred_all,
        "workpiece_usage": np.array(df_tsfresh.loc[x_tsfresh.index[test_idx], "workpiece_usage"])
    })
print("Results von FNO mit tsfresh mit pred_filter")
fno_tsfresh_results = evaluate_folds(fold_results_tsfresh)
fno_tsfresh_results.to_csv('fno_tsfresh_results.csv', index=False)
fno_tsfresh_results

Fold 1 von 5
Fold 2 von 5
Fold 3 von 5
Fold 4 von 5
Fold 5 von 5
Results von FNO mit tsfresh mit pred_filter

,Labelstrategie,Accuracy_mean,Accuracy_std,Precision_mean,Precision_std,Recall_mean,Recall_std,F1_macro_mean,F1_macro_std
0,Binary_s1st,79.513207,0.033976,88.370645,0.021587,85.753684,0.035413,86.983915,0.019129
1,Binary_all,74.752000,0.020334,84.451001,0.008962,83.930000,0.036664,84.136143,0.016428
2,Single_s1st,35.615394,0.044846,31.974856,0.046429,33.807699,0.028695,31.310961,0.037913
3,Single_all,30.504000,0.008006,28.533406,0.006558,28.425000,0.008749,28.017231,0.009153
4,Grouped_s1st,45.936145,0.057117,45.753413,0.055087,46.175499,0.059382,44.663497,0.061415
5,Grouped_all,39.544000,0.012953,40.140872,0.008865,39.544000,0.012953,39.554264,0.012458

### Ich bin mir nicht sicher wie sinnvoll das sein soll. Da keine Zeitsequenz zu verarbeiten, aber als solches gebe ich es durch.

## FNO mit Torque + Angle_value

In [29]:
torque = np.array(data_v2_df["torque_values"].tolist(), dtype=np.float32)
angle = np.array(data_v2_df['angle_values'].tolist(), dtype=np.float32)
X_torque_angle = np.stack([torque, angle], axis=2)
X_torque_angle.shape
print(y_labels)

0          001_control-group
1          001_control-group
2          001_control-group
3          001_control-group
4          001_control-group
                ...
12495    402_surface-chipped
12496    402_surface-chipped
12497    402_surface-chipped
12498    402_surface-chipped
12499    402_surface-chipped
Name: class_values, Length: 12500, dtype: object

In [37]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
le = LabelEncoder()
y = le.fit_transform(y)

n_classes_tsfresh = len(np.unique(y))

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_results_torque_angle = []

for fold_num, (train_idx, test_idx) in enumerate(skf.split(X_torque_angle, y), start=1):
    print(f"Fold {fold_num} von 5")

    X_train_fold = X_torque_angle[train_idx]
    X_test_fold = X_torque_angle[test_idx]
    y_train_fold = y[train_idx]
    y_test_fold = y[test_idx]

    scaler = StandardScaler()
    orig_shape = X_train_fold.shape
    orig_shape_test = X_test_fold.shape
    X_train_fold = scaler.fit_transform(X_train_fold.reshape(X_train_fold.shape[0], -1)) #ValueError: Found array with dim 3, while dim <= 2 is required by StandardScaler. umskallieren zu 2d und dann wieder zurück auf 3d
    X_train_fold = X_train_fold.reshape(orig_shape) 
    X_test_fold = scaler.transform(X_test_fold.reshape(X_test_fold.shape[0], -1)) #durch -1 berechnet numpy automatisch die anzahl der spalten also 2*num features. shape[2] geht nicht da sonst nur ein feature
    X_test_fold = X_test_fold.reshape(orig_shape_test)
    
    x_train_tensor = torch.from_numpy(X_train_fold).float()
    y_train_tensor = torch.from_numpy(y_train_fold).long()

    x_test_tensor = torch.from_numpy(X_test_fold).float()
    y_test_tensor = torch.from_numpy(y_test_fold).long()

    train_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x_train_tensor, y_train_tensor),
        batch_size=batch_size,
        shuffle=True
    )
    test_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x_test_tensor, y_test_tensor),
        batch_size=batch_size,
        shuffle=False
    )

    model = FNO2d(modes, width, n_classes=n_classes_tsfresh, input_channels=2).cuda()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=gamma)

    patience = 30
    best_test_f1 = -np.inf
    patience_counter = 0
    best_model_state = None

    for ep in range(epochs):
        model.train()
        train_cross_entropy = 0.0

        for x, y_batch in train_loader:
            x, y_batch = x.cuda(), y_batch.cuda()
            optimizer.zero_grad()
            out = model(x)
            loss = F.cross_entropy(out, y_batch)
            loss.backward()
            optimizer.step()

            train_cross_entropy += loss.item()
            acc_metric.update(out, y_batch)
            f1_metric.update(out, y_batch)

        epoch_acc = acc_metric.compute()
        epoch_f1 = f1_metric.compute()
        acc_metric.reset()
        f1_metric.reset()

        scheduler.step()
        model.eval()
        test_cross_entropy = 0.0

        with torch.no_grad():
            for x, y_batch in test_loader:
                x, y_batch = x.cuda(), y_batch.cuda()
                out = model(x)
                test_cross_entropy += F.cross_entropy(out, y_batch).item()
                acc_metric.update(out, y_batch)
                f1_metric.update(out, y_batch)

        test_cross_entropy /= len(test_loader)
        epoch_acc = acc_metric.compute()
        epoch_f1 = f1_metric.compute()
        acc_metric.reset()
        f1_metric.reset()

        if float(epoch_f1) > best_test_f1:
            best_test_f1 = float(epoch_f1)
            best_model_state = model.state_dict().copy()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                if best_model_state is not None:
                    model.load_state_dict(best_model_state)
                break

    y_pred_fold = []
    model.eval()
    with torch.no_grad():
        for x, _ in test_loader:
            x = x.cuda()
            out = model(x)
            y_pred_fold.append(out.argmax(dim=1).cpu().numpy())

    y_pred_all = np.concatenate(y_pred_fold)

    fold_results_torque_angle.append({
        "fold": fold_num,
        "True_label": y_test_fold,
        "Pred_label": y_pred_all,
        "workpiece_usage": usage[test_idx]
    })
    
print("Results von FNO 2D mit torque_angle mit pred_filter")
fno_torque_angle_results = evaluate_folds(fold_results_torque_angle)
fno_torque_angle_results.to_csv('fno_torque_angle_results.csv', index=False)
fno_torque_angle_results

Fold 1 von 5
Fold 2 von 5
Fold 3 von 5
Fold 4 von 5
Fold 5 von 5
Results von FNO 2D mit torque_angle mit pred_filter

,Labelstrategie,Accuracy_mean,Accuracy_std,Precision_mean,Precision_std,Recall_mean,Recall_std,F1_macro_mean,F1_macro_std
0,Binary_s1st,83.541770,0.011562,87.533401,0.028303,92.685120,0.022861,89.968347,0.007946
1,Binary_all,78.576000,0.010985,85.894331,0.014299,87.690000,0.026509,86.739586,0.008641
2,Single_s1st,46.186340,0.062901,46.297197,0.045234,43.684991,0.058164,42.657109,0.055822
3,Single_all,37.904000,0.008438,36.416996,0.008777,36.030000,0.004554,35.835597,0.007025
4,Grouped_s1st,58.023986,0.052685,59.185011,0.062017,57.681392,0.060089,56.932958,0.062047
5,Grouped_all,48.336000,0.012796,48.434140,0.011029,48.336000,0.012796,48.103998,0.012718

## FNO mit torque und Work rotational force (angle*torque)

In [38]:
W = torque * angle
X_torque_W = np.stack([torque, W], axis=2)
print(X_torque_W.shape)

(12500, 800, 2)

In [39]:
le = LabelEncoder()
y = le.fit_transform(y)

n_classes_tsfresh = len(np.unique(y))

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_results_torque_W = []

for fold_num, (train_idx, test_idx) in enumerate(skf.split(X_torque_W, y), start=1):
    print(f"Fold {fold_num} von 5")

    X_train_fold = X_torque_W[train_idx]
    X_test_fold = X_torque_W[test_idx]
    y_train_fold = y[train_idx]
    y_test_fold = y[test_idx]

    scaler = StandardScaler()
    orig_shape = X_train_fold.shape
    orig_shape_test = X_test_fold.shape
    X_train_fold = scaler.fit_transform(X_train_fold.reshape(X_train_fold.shape[0], -1)) #ValueError: Found array with dim 3, while dim <= 2 is required by StandardScaler. umskallieren zu 2d und dann wieder zurück auf 3d
    X_train_fold = X_train_fold.reshape(orig_shape) 
    X_test_fold = scaler.transform(X_test_fold.reshape(X_test_fold.shape[0], -1)) #durch -1 berechnet numpy automatisch die anzahl der spalten also 2*num features. shape[2] geht nicht da sonst nur ein feature
    X_test_fold = X_test_fold.reshape(orig_shape_test)
    
    x_train_tensor = torch.from_numpy(X_train_fold).float()
    y_train_tensor = torch.from_numpy(y_train_fold).long()

    x_test_tensor = torch.from_numpy(X_test_fold).float()
    y_test_tensor = torch.from_numpy(y_test_fold).long()

    train_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x_train_tensor, y_train_tensor),
        batch_size=batch_size,
        shuffle=True
    )
    test_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x_test_tensor, y_test_tensor),
        batch_size=batch_size,
        shuffle=False
    )

    model = FNO2d(modes, width, n_classes=n_classes_tsfresh, input_channels=2).cuda()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=step_size, gamma=gamma)

    patience = 30
    best_test_f1 = -np.inf
    patience_counter = 0
    best_model_state = None

    for ep in range(epochs):
        model.train()
        train_cross_entropy = 0.0

        for x, y_batch in train_loader:
            x, y_batch = x.cuda(), y_batch.cuda()
            optimizer.zero_grad()
            out = model(x)
            loss = F.cross_entropy(out, y_batch)
            loss.backward()
            optimizer.step()

            train_cross_entropy += loss.item()
            acc_metric.update(out, y_batch)
            f1_metric.update(out, y_batch)

        epoch_acc = acc_metric.compute()
        epoch_f1 = f1_metric.compute()
        acc_metric.reset()
        f1_metric.reset()

        scheduler.step()
        model.eval()
        test_cross_entropy = 0.0

        with torch.no_grad():
            for x, y_batch in test_loader:
                x, y_batch = x.cuda(), y_batch.cuda()
                out = model(x)
                test_cross_entropy += F.cross_entropy(out, y_batch).item()
                acc_metric.update(out, y_batch)
                f1_metric.update(out, y_batch)

        test_cross_entropy /= len(test_loader)
        epoch_acc = acc_metric.compute()
        epoch_f1 = f1_metric.compute()
        acc_metric.reset()
        f1_metric.reset()

        if float(epoch_f1) > best_test_f1:
            best_test_f1 = float(epoch_f1)
            best_model_state = model.state_dict().copy()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                if best_model_state is not None:
                    model.load_state_dict(best_model_state)
                break

    y_pred_fold = []
    model.eval()
    with torch.no_grad():
        for x, _ in test_loader:
            x = x.cuda()
            out = model(x)
            y_pred_fold.append(out.argmax(dim=1).cpu().numpy())

    y_pred_all = np.concatenate(y_pred_fold)

    fold_results_torque_W.append({
        "fold": fold_num,
        "True_label": y_test_fold,
        "Pred_label": y_pred_all,
        "workpiece_usage": usage[test_idx]
    })
    
print("Results von FNO 2D mit torque_W mit pred_filter")
fno_torque_W_results = evaluate_folds(fold_results_torque_W)
fno_torque_W_results.to_csv('fno_torque_W_results.csv', index=False)
fno_torque_W_results

Fold 1 von 5
Fold 2 von 5
Fold 3 von 5
Fold 4 von 5
Fold 5 von 5
Results von FNO 2D mit torque_W mit pred_filter

,Labelstrategie,Accuracy_mean,Accuracy_std,Precision_mean,Precision_std,Recall_mean,Recall_std,F1_macro_mean,F1_macro_std
0,Binary_s1st,79.573311,0.020739,87.270939,0.029241,87.186843,0.018990,87.178509,0.013209
1,Binary_all,78.424000,0.009434,87.303900,0.011732,85.500000,0.017880,86.370922,0.006882
2,Single_s1st,45.212974,0.017212,45.214151,0.040200,42.489328,0.031247,42.336821,0.027328
3,Single_all,39.520000,0.004996,37.583038,0.008616,37.505000,0.007269,37.348727,0.007505
4,Grouped_s1st,59.252426,0.022710,59.478642,0.019685,58.957205,0.019834,58.370654,0.020064
5,Grouped_all,49.784000,0.005418,50.017470,0.004774,49.784000,0.005418,49.703757,0.003638

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def pred_filter(fold_results, label="binary", usage1st=True):
    metriken = {"Accuracy": [], "Precision": [], "Recall": [], "F1_macro": []}
    if label == "binary":
        average_method = "binary"
    elif label in ["single", "grouped"]:
        average_method = "macro"
    
    for fold in fold_results:
        y_val = fold["True_label"]
        y_pred = fold["Pred_label"]
        usage_val = fold["workpiece_usage"]
        if usage1st == True:
            usage_filter = usage_val == 0
            y_val_filtered = y_val[usage_filter]
            y_pred_filtered = y_pred[usage_filter]
        else:
            y_val_filtered = y_val
            y_pred_filtered = y_pred
        if label == "binary":
            y_val_binary = []
            y_pred_binary = []
            for l in y_val_filtered:
                if str(l).startswith('0'):
                    y_val_binary.append(0)
                else:
                    y_val_binary.append(1)
            for l in y_pred_filtered:
                if str(l).startswith('0'):
                    y_pred_binary.append(0)
                else:
                    y_pred_binary.append(1)
            y_val_filtered = np.array(y_val_binary)
            y_pred_filtered = np.array(y_pred_binary)
        elif label == "grouped":
            y_val_group = []
            y_pred_group = []
            for l in y_val_filtered:
                if str(l).startswith('0'):
                    y_val_group.append(0)
                elif str(l).startswith('1'):
                    y_val_group.append(1)
                elif str(l).startswith('2') or str(l).startswith('3'):
                    y_val_group.append(2)
                elif str(l).startswith('4') or str(l).startswith('5'):
                    y_val_group.append(3)
                elif str(l).startswith('6') or str(l).startswith('7'):
                    y_val_group.append(4)
            for l in y_pred_filtered:
                if str(l).startswith('0'):
                    y_pred_group.append(0)
                elif str(l).startswith('1'):
                    y_pred_group.append(1)
                elif str(l).startswith('2') or str(l).startswith('3'):
                    y_pred_group.append(2)
                elif str(l).startswith('4') or str(l).startswith('5'):
                    y_pred_group.append(3)
                elif str(l).startswith('6') or str(l).startswith('7'):
                    y_pred_group.append(4)
            y_val_filtered = np.array(y_val_group)
            y_pred_filtered = np.array(y_pred_group)
        elif label == "single":
            y_val_filtered = np.array(y_val_filtered)
            y_pred_filtered = np.array(y_pred_filtered)
        metriken["Accuracy"].append(accuracy_score(y_val_filtered, y_pred_filtered))
        metriken["Precision"].append(precision_score(y_val_filtered, y_pred_filtered, average=average_method, zero_division=0))
        metriken["Recall"].append(recall_score(y_val_filtered, y_pred_filtered, average=average_method, zero_division=0))
        metriken["F1_macro"].append(f1_score(y_val_filtered, y_pred_filtered, average=average_method, zero_division=0))
    
    stats = {"Accuracy_mean": np.mean(metriken["Accuracy"]), "Accuracy_std": np.std(metriken["Accuracy"]), "Precision_mean": np.mean(metriken["Precision"]), "Precision_std": np.std(metriken["Precision"]), "Recall_mean": np.mean(metriken["Recall"]), "Recall_std": np.std(metriken["Recall"]), "F1_macro_mean": np.mean(metriken["F1_macro"]), "F1_macro_std": np.std(metriken["F1_macro"])}
    for i in stats:
        if i != "Accuracy_std" and i != "Precision_std" and i != "Recall_std" and i != "F1_macro_std":
            stats[i] *= 100
    df = pd.DataFrame([stats])
    return df


def evaluate_folds(fold_results):
    df_binary_s1st = pred_filter(fold_results, label="binary", usage1st=True)
    df_binary_all = pred_filter(fold_results, label="binary", usage1st=False)
    df_single_s1st = pred_filter(fold_results, label="single", usage1st=True)
    df_single_all = pred_filter(fold_results, label="single", usage1st=False)
    df_grouped_s1st = pred_filter(fold_results, label="grouped", usage1st=True)
    df_grouped_all = pred_filter(fold_results, label="grouped", usage1st=False)
    
    results = pd.concat([df_binary_s1st, df_binary_all, df_single_s1st, df_single_all, df_grouped_s1st, df_grouped_all], ignore_index=True)

    results.insert(0, 'Labelstrategie', ['Binary_s1st', 'Binary_all', 'Single_s1st', 'Single_all','Grouped_s1st', 'Grouped_all'])
    return results

In [28]:
pred = []
model.eval()
with torch.no_grad():
    for x, y in test_loader:
        x, y = x.cuda(), y.cuda()
        out = model(x)
        preds = out.argmax(dim=1).cpu().numpy()
        pred.append(preds)

y_pred_all = np.concatenate(pred)
y_test_all = y_test_tensor.cpu().numpy()
usage_test_all = np.array(data_v2_df['workpiece_usage'].tolist())[split_idx:]


fold_results = [{
    "True_label": y_test_all,
    "Pred_label": y_pred_all,
    "workpiece_usage": usage_test_all
}]

evaluate_folds(fold_results)

,Labelstrategie,Accuracy_mean,Accuracy_std,Precision_mean,Precision_std,Recall_mean,Recall_std,F1_macro_mean,F1_macro_std
0,Binary_s1st,78.034682,0.0,87.313433,0.0,84.782609,0.0,86.029412,0.0
1,Binary_all,78.651429,0.0,87.027962,0.0,86.183271,0.0,86.603557,0.0
2,Single_s1st,37.572254,0.0,34.710292,0.0,34.339123,0.0,34.052257,0.0
3,Single_all,40.365714,0.0,38.219713,0.0,38.376939,0.0,38.183187,0.0
4,Grouped_s1st,50.289017,0.0,50.490866,0.0,50.829386,0.0,50.078742,0.0
5,Grouped_all,50.560000,0.0,50.899666,0.0,50.613415,0.0,50.675046,0.0